-- ALTER SESSION SET "_ORACLE_SCRIPT" = true;
-- CREATE USER APP IDENTIFIED BY APP123 QUOTA UNLIMITED ON USERS;
-- GRANT connect, resource TO APP;
-- Cria tabela: Concessionarias - OK
-- Cria tabela: Rodovias - OK
-- Cria tabela: Municípios - OK
-- Cria tabela: Condições climaticas - OK
-- Cria tabela: Tipos acidentes - OK
-- Cria tabela: Acidentes - PENDENTE
-- Cria tabela: Tipos veiculos - PENDENTE
-- Cria tabela: Veiculos envolvidos - PENDENTE
-- CRIAR A TABELA DE MUNICIPIOS
CREATE SEQUENCE SEQ_MUNICIPIOS_ID NOCACHE;

-- ALTER SEQUENCE <nome da sequencia> RESTART;
CREATE TABLE
    MUNICIPIOS AS
SELECT
    SEQ_MUNICIPIOS_ID.NEXTVAL AS MUN_ID,
    DADOS_2.MUNICÍPIO
FROM
    (
        SELECT DISTINCT
            MUNICÍPIO
        FROM
            DADOS
    ) DADOS_2;

-- CRIAR A TABELA DE CONCESSIONARIAS
CREATE SEQUENCE SEQ_CONCESSIONARIAS_ID NOCACHE;

-- ALTER SEQUENCE <nome da sequencia> RESTART;
CREATE TABLE
    CONCESSIONARIAS AS
SELECT
    SEQ_CONCESSIONARIAS_ID.NEXTVAL AS CONC_ID,
    DADOS_2.NOME_CONC
FROM
    (
        SELECT DISTINCT
            NOME_CONC
        FROM
            DADOS
    ) DADOS_2;

-- CRIAR A TABELA DE RODOVIAS
CREATE SEQUENCE SEQ_RODOVIAS_ID NOCACHE;

-- ALTER SEQUENCE <nome da sequencia> RESTART;
CREATE TABLE
    RODOVIAS AS
SELECT
    SEQ_RODOVIAS_ID.NEXTVAL AS ROD_ID,
    DADOS_2.RODOVIA,
    DADOS_2.DENOMINACAO,
    DADOS_2.JURISDICAO,
    DADOS_2.CONC_ID
FROM
    (
        SELECT DISTINCT
            R.RODOVIA,
            R.DENOMINACAO,
            R.JURISDICAO,
            C.CONC_ID
        FROM
            DADOS R
            LEFT JOIN CONCESSIONARIAS C ON R.NOME_CONC = C.NOME_CONC
    ) DADOS_2;

-- CRIAR A TABELA DE CONDICOES CLIMATICAS
CREATE SEQUENCE SEQ_COND_CLIMA_ID NOCACHE;

-- ALTER SEQUENCE <nome da sequencia> RESTART;
CREATE TABLE
    CONDICOES_CLIMATICA AS
SELECT
    SEQ_COND_CLIMA_ID.NEXTVAL AS COND_ID,
    DADOS_2.METEORO,
    DADOS_2.VISIB
FROM
    (
        SELECT DISTINCT
            METEORO,
            VISIB
        FROM
            DADOS
    ) DADOS_2;

-- CRIAR A TABELA DE TIPOS DE ACIDENTES
CREATE SEQUENCE SEQ_TP_ACIDENTES_ID NOCACHE;

-- ALTER SEQUENCE <nome da sequencia> RESTART;
CREATE TABLE
    TIPOS_ACIDENTES AS
SELECT
    SEQ_TP_ACIDENTES_ID.NEXTVAL AS TP_ACIDENTES_ID,
    DADOS_2.CLASS_ACID,
    DADOS_2.TIPO_ACID
FROM
    (
        SELECT DISTINCT
            CLASS_ACID,
            TIPO_ACID
        FROM
            DADOS
    ) DADOS_2;

-- CRIAR A TABELA DE ACIDENTES
CREATE SEQUENCE SEQ_ACIDENTES_ID NOCACHE;

-- ALTER SEQUENCE <nome da sequencia> RESTART;
CREATE TABLE
    ACIDENTES AS -- DROP TABLE ACIDENTES;
SELECT
    SEQ_ACIDENTES_ID.NEXTVAL AS ACD_ID,
    DADOS_2.MARCO_QM,
    DADOS_2.SENTIDO,
    DADOS_2.DTHR_OC,
    DADOS_2.ANO,
    DADOS_2.MÊS,
    DADOS_2.ILESA_INT,
    DADOS_2.VIT_FATAL_INT,
    DADOS_2.VIT_GRAVE_INT,
    DADOS_2.VIT_LEVE_INT,
    DADOS_2.VIT_MODERADA_INT,
    DADOS_2.VIT_SEMINFO_INT,
    DADOS_2.TIPO_PISTA,
    DADOS_2.LAT_FINAL,
    DADOS_2.LON_FINAL,
    DADOS_2.ROD_ID
FROM
    (
        SELECT
            D.MARCO_QM,
            D.SENTIDO,
            D.DTHR_OC,
            D.ANO,
            MÊS,
            D.ILESA_INT,
            D.VIT_FATAL_INT,
            D.VIT_GRAVE_INT,
            D.VIT_LEVE_INT,
            D.VIT_MODERADA_INT,
            D.VIT_SEMINFO_INT,
            D.TIPO_PISTA,
            D.LAT_FINAL,
            D.LON_FINAL,
            R.CONC_ID AS ROD_ID
        FROM
            DADOS D
            INNER JOIN CONCESSIONARIAS C ON D.NOME_CONC = C.NOME_CONC
            INNER JOIN RODOVIAS R ON R.CONC_ID = C.CONC_ID
        WHERE
            D.NOME_CONC = C.NOME_CONC
            AND D.RODOVIA = R.RODOVIA
            AND D.DENOMINACAO = R.DENOMINACAO
            AND D.JURISDICAO = R.JURISDICAO
            AND R.CONC_ID = C.CONC_ID
    ) DADOS_2;

-- CRIAR A TABELA DE TIPOS DE VEICULOS
CREATE SEQUENCE SEQ_TP_VEICULOS_ID NOCACHE;

-- ALTER SEQUENCE <nome da sequencia> RESTART;
CREATE TABLE
    TIPOS_VEICULOS AS
SELECT
    SEQ_TP_VEICULOS_ID.NEXTVAL AS TP_VEICULOS_ID,
    DADOS_2.CLASS_ACID,
    DADOS_2.TIPO_ACID
FROM
    (
        SELECT DISTINCT
            CLASS_ACID,
            TIPO_ACID
        FROM
            DADOS
    ) DADOS_2;

CREATE SEQUENCE SEQ_TEMP_VEICULO_ID NOCACHE;

SELECT
    t1.ID_LINHA,
    TRIM(
        SUBSTR (
            t2.PAR_VEICULO,
            1,
            INSTR (t2.PAR_VEICULO, '=') - 1
        )
    ) AS TIPO_VEICULO,
    TO_NUMBER (
        SUBSTR (t2.PAR_VEICULO, INSTR (t2.PAR_VEICULO, '=') + 1)
    ) AS QUANTIDADE
FROM
    (
        -- Sub-query para criar um ID temporário (ROWNUM) para cada linha da tabela DADOS
        SELECT
            ROWNUM AS ID_LINHA,
            VEÍC
        FROM
            DADOS
    ) t1
    JOIN (
        -- Sub-query para "explodir" a string e gerar uma linha para cada par
        SELECT
            ROWNUM AS ID_LINHA,
            TRIM(REGEXP_SUBSTR (t.VEÍC, '[^|]+', 1, LEVEL)) AS PAR_VEICULO
        FROM
            DADOS t CONNECT BY LEVEL <= REGEXP_COUNT (t.VEÍC, '[|]') + 1
            AND PRIOR t.VEÍC = t.VEÍC
    ) t2 ON t1.ID_LINHA = t2.ID_LINHA
WHERE
    t2.PAR_VEICULO IS NOT NULL;



-- CRIAR A TABELA DE ACIDENTES
CREATE SEQUENCE SEQ_ACIDENTES_ID NOCACHE;  -- ALTER SEQUENCE <nome da sequencia> RESTART;

CREATE TABLE ACIDENTES AS -- DROP TABLE ACIDENTES;
SELECT 
    SEQ_ACIDENTES_ID.NEXTVAL AS ACD_ID,
    DADOS_2.MARCO_QM,
    DADOS_2.SENTIDO,
    DADOS_2.DTHR_OC,
    DADOS_2.ANO,
    DADOS_2.MÊS,
    DADOS_2.ILESA_INT,
    DADOS_2.VIT_FATAL_INT,
    DADOS_2.VIT_GRAVE_INT,
    DADOS_2.VIT_LEVE_INT,
    DADOS_2.VIT_MODERADA_INT,
    DADOS_2.VIT_SEMINFO_INT,
    DADOS_2.TIPO_PISTA,
    DADOS_2.LAT_FINAL,
    DADOS_2.LON_FINAL,
    DADOS_2.ROD_ID
FROM 
    (SELECT 
        D.MARCO_QM, 
        D.SENTIDO, 
        D.DTHR_OC, 
        D.ANO, MÊS,
        D.ILESA_INT, 
        D.VIT_FATAL_INT, 
        D.VIT_GRAVE_INT, 
        D.VIT_LEVE_INT, 
        D.VIT_MODERADA_INT, 
        D.VIT_SEMINFO_INT, 
        D.TIPO_PISTA,
        D.LAT_FINAL, 
        D.LON_FINAL,
        R.CONC_ID AS ROD_ID
    FROM DADOS D
    INNER JOIN CONCESSIONARIAS C ON D.NOME_CONC = C.NOME_CONC
    INNER JOIN RODOVIAS R ON R.CONC_ID = C.CONC_ID
    WHERE D.NOME_CONC = C.NOME_CONC 
        AND D.RODOVIA = R.RODOVIA 
        AND D.DENOMINACAO = R.DENOMINACAO
        AND D.JURISDICAO = R.JURISDICAO
        AND R.CONC_ID = C.CONC_ID) DADOS_2;





    
-- SCRIPT PARA SEPARA O VALOR DE VEICULOS
SELECT ID,
       REGEXP_SUBSTR(item, '[^=]+', 1, 1) AS TIPO_VEICULO,
       TO_NUMBER(REGEXP_SUBSTR(item, '[^=]+', 1, 2)) AS QUANTIDADE
FROM (
    SELECT ID,
           REGEXP_SUBSTR(VEÍC, '[^|]+', 1, LEVEL) AS item
    FROM DADOS
    CONNECT BY REGEXP_SUBSTR(VEÍC, '[^|]+', 1, LEVEL) IS NOT NULL
           AND PRIOR ID = ID
           AND PRIOR SYS_GUID() IS NOT NULL
);

