INSERT INTO TESTE(TESTE_ID, TESTE_NOME) VALUES (1, 'Teste 1');
INSERT INTO TESTE(TESTE_ID, TESTE_NOME) VALUES (2, 'Teste 2');
INSERT INTO TESTE(TESTE_ID, TESTE_NOME) VALUES (3, 'Teste 3');
INSERT INTO TESTE(TESTE_ID, TESTE_NOME) VALUES (4, 'Teste 4');