--------------------------------------------------------------------------------
--                                                                            --
--  TRIGGERS                                                                  --
--                                                                            --
--  SCRIPTS PARA CRIAR AS TRIGGERS QUE EXECUTAM O HISTORIAMENTO               --
--                                                                            --
--------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_MUNICIPIOS
AFTER DELETE OR UPDATE ON MUNICIPIOS
FOR EACH ROW
BEGIN
    INSERT INTO H_MUNICIPIOS(OLD_MUN_ID, OLD_MUN_MUNICIPIO, OLD_MUN_REG_DER, OLD_MUN_REG_ADM) VALUES (
        :OLD.MUN_ID, 
        :OLD.MUN_MUNICIPIO, 
        :OLD.MUN_REG_DER, 
        :OLD.MUN_REG_ADM);
END;
/

CREATE OR REPLACE TRIGGER TRG_CONDICOES_CLIMATICAS
AFTER DELETE OR UPDATE ON CONDICOES_CLIMATICAS
FOR EACH ROW
BEGIN
    INSERT INTO H_CONDICOES_CLIMATICAS(OLD_CCM_ID, OLD_CCM_METEORO, OLD_CCM_VISIB) 
    VALUES (:OLD.CCM_ID, :OLD.CCM_METEORO, :OLD.CCM_VISIB);
END;
/

CREATE OR REPLACE TRIGGER TRG_CONCESSIONARIAS
AFTER DELETE OR UPDATE ON CONCESSIONARIAS
FOR EACH ROW
BEGIN
    INSERT INTO H_CONCESSIONARIAS (OLD_CON_ID, OLD_CON_CONCESSIONARIA)
    VALUES (:OLD.CON_ID, :OLD.CON_CONCESSIONARIA);
END;
/

CREATE OR REPLACE TRIGGER TRG_RODOVIAS
AFTER DELETE OR UPDATE ON RODOVIAS
FOR EACH ROW
BEGIN
    INSERT INTO H_RODOVIAS(
        OLD_ROD_ID, 
        OLD_ROD_CODIGO_RODOVIA, 
        OLD_ROD_DENOMINACAO, 
        OLD_ROD_JURISDICAO, 
        OLD_ROD_CON_ID)
    VALUES (
        :OLD.ROD_ID, 
        :OLD.ROD_CODIGO_RODOVIA,
        :OLD.ROD_DENOMINACAO,
        :OLD.ROD_JURISDICAO,
        :OLD.ROD_CON_ID
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_TIPOS_ACIDENTES
AFTER DELETE OR UPDATE ON TIPOS_ACIDENTES
FOR EACH ROW
BEGIN
    INSERT INTO H_TIPOS_ACIDENTES(
        OLD_TAC_ID, 
        OLD_TAC_CLASS_ACID, 
        OLD_TAC_TIPO_ACID)
     VALUES (
        :OLD.TAC_ID, 
        :OLD.TAC_CLASS_ACID,
        :OLD.TAC_TIPO_ACID
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_TIPOS_VEICULOS
AFTER DELETE OR UPDATE ON TIPOS_VEICULOS
FOR EACH ROW
BEGIN
    INSERT INTO H_TIPOS_VEICULOS(OLD_TVC_ID, OLD_TVC_VEICULO) 
    VALUES (:OLD.TVC_ID, :OLD.TVC_VEICULO);
END;
/

CREATE OR REPLACE TRIGGER TRG_ACIDENTES
AFTER DELETE OR UPDATE ON ACIDENTES
FOR EACH ROW
BEGIN
    INSERT INTO H_ACIDENTES(
        OLD_ACD_ID,
        OLD_ACD_MARCO_QM,
        OLD_ACD_SENTIDO,
        OLD_ACD_DTHR_OC,
        OLD_ACD_ANO,
        OLD_ACD_MES,
        OLD_ACD_ILESA_INT,
        OLD_ACD_VIT_FATAL_INT,
        OLD_ACD_VIT_GRAVE_INT,
        OLD_ACD_VIT_LEVE_INT,
        OLD_ACD_VIT_MODERADA_INT,
        OLD_ACD_VIT_SEMINFO_INT,
        OLD_ACD_TIPO_PISTA,
        OLD_ACD_LAT_FINAL,
        OLD_ACD_LON_FINAL,
        OLD_ACD_ROD_ID,
        OLD_ACD_TAC_ID,
        OLD_ACD_CCM_ID,
        OLD_ACD_MUN_ID
    ) 
    VALUES (
        :OLD.ACD_ID,
        :OLD.ACD_MARCO_QM,
        :OLD.ACD_SENTIDO,
        :OLD.ACD_DTHR_OC,
        :OLD.ACD_ANO,
        :OLD.ACD_MES,
        :OLD.ACD_ILESA_INT,
        :OLD.ACD_VIT_FATAL_INT,
        :OLD.ACD_VIT_GRAVE_INT,
        :OLD.ACD_VIT_LEVE_INT,
        :OLD.ACD_VIT_MODERADA_INT,
        :OLD.ACD_VIT_SEMINFO_INT,
        :OLD.ACD_TIPO_PISTA,
        :OLD.ACD_LAT_FINAL,
        :OLD.ACD_LON_FINAL,
        :OLD.ACD_ROD_ID,
        :OLD.ACD_TAC_ID,
        :OLD.ACD_CCM_ID,
        :OLD.ACD_MUN_ID
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_VEICULOS_ENVOLVIDOS
AFTER DELETE OR UPDATE ON VEICULOS_ENVOLVIDOS
FOR EACH ROW
BEGIN
    INSERT INTO H_VEICULOS_ENVOLVIDOS(
        OLD_VEN_ID,
        OLD_VEN_QTD,
        OLD_VEN_ACD_ID,
        OLD_VEN_TVC_ID
    ) 
    VALUES (
        :OLD.VEN_ID,
        :OLD.VEN_QTD,
        :OLD.VEN_ACD_ID,
        :OLD.VEN_TVC_ID
    );
END;
/