DROP TRIGGER TRG_H_MUNICIPIOS;
DROP TRIGGER TRG_H_CONDICOES_CLIMATICAS;
DROP TRIGGER TRG_H_CONCESSIONARIAS;
DROP TRIGGER TRG_H_RODOVIAS;
DROP TRIGGER TRG_H_TIPOS_ACIDENTES;
DROP TRIGGER TRG_H_TIPOS_VEICULOS;
DROP TRIGGER TRG_H_ACIDENTES;
DROP TRIGGER TRG_H_VEICULOS_ENVOLVIDOS;

DROP TABLE H_VEICULOS_ENVOLVIDOS;
DROP TABLE H_ACIDENTES;
DROP TABLE H_TIPOS_VEICULOS;
DROP TABLE H_TIPOS_ACIDENTES;
DROP TABLE H_RODOVIAS;
DROP TABLE H_CONCESSIONARIAS;
DROP TABLE H_CONDICOES_CLIMATICAS;
DROP TABLE H_MUNICIPIOS;
