--------------------------------------------------------------------------------
--  HISTORIAMENTO                                                             --
--  SCRIPTS PARA CRIAR AS ENTIDADES DE HISTORIAMENTO                          --
--------------------------------------------------------------------------------
CREATE TABLE H_MUNICIPIOS (
    H_MUN_ID NUMBER (38),
    H_MUN_MUNICIPIO VARCHAR2(100),
    H_MUN_REG_DER VARCHAR2(100),
    H_MUN_REG_ADM VARCHAR2(100),
    H_MUN_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(H_MUN_ID, H_MUN_CREATED_AT)
);


CREATE TABLE H_CONDICOES_CLIMATICAS (
    H_CCM_ID NUMBER (38), 
    H_CCM_METEORO VARCHAR2(100),
    H_CCM_VISIB VARCHAR2(100),
    H_CCM_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(H_CCM_ID, H_CCM_CREATED_AT)
);

CREATE TABLE H_CONCESSIONARIAS (
    H_CON_ID NUMBER (38), 
    H_CON_CONCESSIONARIA VARCHAR2(100),
    H_CON_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(H_CON_ID, H_CON_CREATED_AT)
);

CREATE TABLE H_RODOVIAS (
    H_ROD_ID NUMBER (38), 
    H_ROD_CODIGO_RODOVIA VARCHAR2(100),
    H_ROD_DENOMINACAO VARCHAR2(100),
    H_ROD_JURISDICAO VARCHAR2(100),
    H_ROD_CON_ID NUMBER(38),
    H_ROD_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(H_ROD_ID, H_ROD_CREATED_AT)
);

CREATE TABLE H_TIPOS_ACIDENTES (
    H_TAC_ID NUMBER (38), 
    H_TAC_CLASS_ACID VARCHAR2(100),
    H_TAC_TIPO_ACID VARCHAR2(100),
    H_TAC_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(H_TAC_ID, H_TAC_CREATED_AT)
);

CREATE TABLE H_TIPOS_VEICULOS (
    H_TVC_ID NUMBER (38), 
    H_TVC_VEICULO VARCHAR2(100),
    H_TVC_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(H_TVC_ID, H_TVC_CREATED_AT)
);

CREATE TABLE H_ACIDENTES (
    H_ACD_ID NUMBER(38),
    H_ACD_MARCO_QM NUMBER(38),
    H_ACD_SENTIDO VARCHAR2(100),
    H_ACD_DTHR_OC DATE,
    H_ACD_ANO NUMBER(38),
    H_ACD_MES NUMBER(38),
    H_ACD_ILESA_INT NUMBER(38),
    H_ACD_VIT_FATAL_INT NUMBER(38),
    H_ACD_VIT_GRAVE_INT NUMBER(38),
    H_ACD_VIT_LEVE_INT NUMBER(38),
    H_ACD_VIT_MODERADA_INT NUMBER(38),
    H_ACD_VIT_SEMINFO_INT NUMBER(38),
    H_ACD_TIPO_PISTA VARCHAR2(100),
    H_ACD_LAT_FINAL NUMBER(38),
    H_ACD_LON_FINAL NUMBER(38),
    H_ACD_ROD_ID NUMBER(38),
    H_ACD_TAC_ID NUMBER(38),
    H_ACD_CCM_ID NUMBER(38),
    H_ACD_MUN_ID NUMBER(38),
    H_ACD_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(H_ACD_ID, H_ACD_CREATED_AT)
);

CREATE TABLE H_VEICULOS_ENVOLVIDOS (
    H_VEN_ID NUMBER(38),
    H_VEN_QTD NUMBER(38),
    H_VEN_ACD_ID NUMBER(38),
    H_VEN_TVC_ID NUMBER(38),
    H_VEN_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(H_VEN_ID, H_VEN_CREATED_AT)
);