--------------------------------------------------------------------------------
--  TRIGGERS                                                                  --
--  SCRIPTS PARA CRIAR AS TRIGGERS QUE EXECUTAM O HISTORIAMENTO               --
--------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_MUNICIPIOS
AFTER DELETE OR UPDATE ON MUNICIPIOS
FOR EACH ROW
BEGIN
    INSERT INTO H_MUNICIPIOS(H_MUN_ID, H_MUN_MUNICIPIO, H_MUN_REG_DER, H_MUN_REG_ADM) VALUES (
        :OLD.MUN_ID, 
        :OLD.MUN_MUNICIPIO, 
        :OLD.MUN_REG_DER, 
        :OLD.MUN_REG_ADM);
END;
/

CREATE OR REPLACE TRIGGER TRG_CONDICOES_CLIMATICAS
AFTER DELETE OR UPDATE ON CONDICOES_CLIMATICAS
FOR EACH ROW
BEGIN
    INSERT INTO H_CONDICOES_CLIMATICAS(H_CCM_ID, H_CCM_METEORO, H_CCM_VISIB) 
    VALUES (:OLD.CCM_ID, :OLD.CCM_METEORO, :OLD.CCM_VISIB);
END;
/

CREATE OR REPLACE TRIGGER TRG_CONCESSIONARIAS
AFTER DELETE OR UPDATE ON CONCESSIONARIAS
FOR EACH ROW
BEGIN
    INSERT INTO H_CONCESSIONARIAS (H_CON_ID, H_CON_CONCESSIONARIA)
    VALUES (:OLD.CON_ID, :OLD.CON_CONCESSIONARIA);
END;
/

CREATE OR REPLACE TRIGGER TRG_RODOVIAS
AFTER DELETE OR UPDATE ON RODOVIAS
FOR EACH ROW
BEGIN
    INSERT INTO H_RODOVIAS(
        H_ROD_ID, 
        H_ROD_CODIGO_RODOVIA, 
        H_ROD_DENOMINACAO, 
        H_ROD_JURISDICAO, 
        H_ROD_CON_ID)
    VALUES (
        :OLD.ROD_ID, 
        :OLD.ROD_CODIGO_RODOVIA,
        :OLD.ROD_DENOMINACAO,
        :OLD.ROD_JURISDICAO,
        :OLD.ROD_CON_ID
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_TIPOS_ACIDENTES
AFTER DELETE OR UPDATE ON TIPOS_ACIDENTES
FOR EACH ROW
BEGIN
    INSERT INTO H_TIPOS_ACIDENTES(
        H_TAC_ID, 
        H_TAC_CLASS_ACID, 
        H_TAC_TIPO_ACID)
     VALUES (
        :OLD.TAC_ID, 
        :OLD.TAC_CLASS_ACID,
        :OLD.TAC_TIPO_ACID
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_TIPOS_VEICULOS
AFTER DELETE OR UPDATE ON TIPOS_VEICULOS
FOR EACH ROW
BEGIN
    INSERT INTO H_TIPOS_VEICULOS(H_TVC_ID, H_TVC_VEICULO) 
    VALUES (:OLD.TVC_ID, :OLD.TVC_VEICULO);
END;
/

CREATE OR REPLACE TRIGGER TRG_ACIDENTES
AFTER DELETE OR UPDATE ON ACIDENTES
FOR EACH ROW
BEGIN
    INSERT INTO H_ACIDENTES(
        H_ACD_ID,
        H_ACD_MARCO_QM,
        H_ACD_SENTIDO,
        H_ACD_DTHR_OC,
        H_ACD_ANO,
        H_ACD_MES,
        H_ACD_ILESA_INT,
        H_ACD_VIT_FATAL_INT,
        H_ACD_VIT_GRAVE_INT,
        H_ACD_VIT_LEVE_INT,
        H_ACD_VIT_MODERADA_INT,
        H_ACD_VIT_SEMINFO_INT,
        H_ACD_TIPO_PISTA,
        H_ACD_LAT_FINAL,
        H_ACD_LON_FINAL,
        H_ACD_ROD_ID,
        H_ACD_TAC_ID,
        H_ACD_CCM_ID,
        H_ACD_MUN_ID
    ) 
    VALUES (
        :OLD.ACD_ID,
        :OLD.ACD_MARCO_QM,
        :OLD.ACD_SENTIDO,
        :OLD.ACD_DTHR_OC,
        :OLD.ACD_ANO,
        :OLD.ACD_MES,
        :OLD.ACD_ILESA_INT,
        :OLD.ACD_VIT_FATAL_INT,
        :OLD.ACD_VIT_GRAVE_INT,
        :OLD.ACD_VIT_LEVE_INT,
        :OLD.ACD_VIT_MODERADA_INT,
        :OLD.ACD_VIT_SEMINFO_INT,
        :OLD.ACD_TIPO_PISTA,
        :OLD.ACD_LAT_FINAL,
        :OLD.ACD_LON_FINAL,
        :OLD.ACD_ROD_ID,
        :OLD.ACD_TAC_ID,
        :OLD.ACD_CCM_ID,
        :OLD.ACD_MUN_ID
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_VEICULOS_ENVOLVIDOS
AFTER DELETE OR UPDATE ON VEICULOS_ENVOLVIDOS
FOR EACH ROW
BEGIN
    INSERT INTO H_VEICULOS_ENVOLVIDOS(
        H_VEN_ID,
        H_VEN_QTD,
        H_VEN_ACD_ID,
        H_VEN_TVC_ID
    ) 
    VALUES (
        :OLD.VEN_ID,
        :OLD.VEN_QTD,
        :OLD.VEN_ACD_ID,
        :OLD.VEN_TVC_ID
    );
END;
/