-- TESTE DO HISTORIAMENTO
-- Alterando os valores para envia-los para o historiamento
SELECT * FROM ACIDENTES WHERE ACD_ID = 127576;

-- UPDATE ACIDENTES SET ACD_SENTIDO = 'LESTE' WHERE ACD_ID = 127576; -- VALORES ORIGINAIS
-- UPDATE ACIDENTES SET ACD_TIPO_PISTA = 'EIXO' WHERE ACD_ID = 127576; -- VALORES ORIGINAIS
-- UPDATE ACIDENTES SET ACD_ROD_ID = 295 WHERE ACD_ID = 127576; -- VALORES ORIGINAIS

UPDATE ACIDENTES SET ACD_SENTIDO = 'NORTE' WHERE ACD_ID = 127576; -- VALORES ALTERADO
UPDATE ACIDENTES SET ACD_TIPO_PISTA = 'INTERLIGAÇÃO' WHERE ACD_ID = 127576; -- VALORES ALTERADO
UPDATE ACIDENTES SET ACD_ROD_ID = 296 WHERE ACD_ID = 127576; -- VALORES ALTERADO

SELECT * FROM H_ACIDENTES ORDER BY H_ACD_CREATED_AT DESC;