DROP TRIGGER TRG_AUD_H_CONCESSIONARIA;
DROP TRIGGER TRG_AUD_H_RODOVIAS;
DROP TRIGGER TRG_AUD_H_MUNICIPIOS;
DROP TRIGGER TRG_AUD_H_TIPOS_ACIDENTES;
DROP TRIGGER TRG_AUD_H_CONDICOES_CLIMATICAS;
DROP TRIGGER TRG_AUD_H_TIPOS_VEICULOS;
DROP TRIGGER TRG_AUD_H_ACIDENTES;
DROP TRIGGER TRG_AUD_H_VEICULOS_ENVOLVIDOS;

DROP TRIGGER TRG_SEQ_AUD;

DROP SEQUENCE SEQ_AUD;

DROP PROCEDURE PROC_AUDITORIA;

DROP TABLE AUDITORIA;