--------------------------------------------------------
--  DDL for Trigger TRG_AUD_H_CONCESSIONARIA
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_AUD_H_CONCESSIONARIA" 
AFTER UPDATE OR DELETE ON APP.H_CONCESSIONARIAS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR2(20);
    V_TABELA VARCHAR2(30) := 'H_CONCESSIONARIAS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_CON_ID', :OLD.H_CON_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_CON_CONCESSIONARIA', :OLD.H_CON_CONCESSIONARIA, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.H_CON_ID <> :OLD.H_CON_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_CON_ID', :OLD.H_CON_ID, :NEW.H_CON_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_CON_CONCESSIONARIA <> :OLD.H_CON_CONCESSIONARIA) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_CON_CONCESSIONARIA', :OLD.H_CON_CONCESSIONARIA, :NEW.H_CON_CONCESSIONARIA, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TRG_AUD_H_CONCESSIONARIA" ENABLE;


--------------------------------------------------------
--  DDL for Trigger TRG_AUD_H_RODOVIAS
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_AUD_H_RODOVIAS" 
AFTER UPDATE OR DELETE ON APP.H_RODOVIAS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR2(20);
    V_TABELA VARCHAR2(30) := 'H_RODOVIAS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ROD_ID', :OLD.H_ROD_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ROD_CODIGO_RODOVIA', :OLD.H_ROD_CODIGO_RODOVIA, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ROD_DENOMINACAO', :OLD.H_ROD_DENOMINACAO, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ROD_JURISDICAO', :OLD.H_ROD_JURISDICAO, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ROD_CON_ID', :OLD.H_ROD_CON_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.H_ROD_ID <> :OLD.H_ROD_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ROD_ID', :OLD.H_ROD_ID, :NEW.H_ROD_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ROD_CODIGO_RODOVIA <> :OLD.H_ROD_CODIGO_RODOVIA) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ROD_CODIGO_RODOVIA', :OLD.H_ROD_CODIGO_RODOVIA, :NEW.H_ROD_CODIGO_RODOVIA, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ROD_DENOMINACAO <> :OLD.H_ROD_DENOMINACAO) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ROD_DENOMINACAO', :OLD.H_ROD_DENOMINACAO, :NEW.H_ROD_DENOMINACAO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ROD_JURISDICAO <> :OLD.H_ROD_JURISDICAO) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ROD_JURISDICAO', :OLD.H_ROD_JURISDICAO, :NEW.H_ROD_JURISDICAO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ROD_CON_ID <> :OLD.H_ROD_CON_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ROD_CON_ID', :OLD.H_ROD_CON_ID, :NEW.H_ROD_CON_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TRG_AUD_H_RODOVIAS" ENABLE;

--------------------------------------------------------
--  DDL for Trigger TRG_AUD_H_MUNICIPIOS
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_AUD_H_MUNICIPIOS" 
AFTER UPDATE OR DELETE ON APP.H_MUNICIPIOS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR2(20);
    V_TABELA VARCHAR2(30) := 'H_MUNICIPIOS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_MUN_ID', :OLD.H_MUN_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_MUN_MUNICIPIO', :OLD.H_MUN_MUNICIPIO, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_MUN_REG_DER', :OLD.H_MUN_REG_DER, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_MUN_REG_ADM', :OLD.H_MUN_REG_ADM, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.H_MUN_ID <> :OLD.H_MUN_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_MUN_ID', :OLD.H_MUN_ID, :NEW.H_MUN_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_MUN_MUNICIPIO <> :OLD.H_MUN_MUNICIPIO) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_MUN_MUNICIPIO', :OLD.H_MUN_MUNICIPIO, :NEW.H_MUN_MUNICIPIO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_MUN_REG_DER <> :OLD.H_MUN_REG_DER) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_MUN_REG_DER', :OLD.H_MUN_REG_DER, :NEW.H_MUN_REG_DER, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_MUN_REG_ADM <> :OLD.H_MUN_REG_ADM) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_MUN_REG_ADM', :OLD.H_MUN_REG_ADM, :NEW.H_MUN_REG_ADM, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TRG_AUD_H_MUNICIPIOS" ENABLE;

--------------------------------------------------------
--  DDL for Trigger TRG_AUD_H_TIPOS_ACIDENTES
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_AUD_H_TIPOS_ACIDENTES" 
AFTER UPDATE OR DELETE ON APP.H_TIPOS_ACIDENTES
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR2(20);
    V_TABELA VARCHAR2(30) := 'H_TIPOS_ACIDENTES';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_TAC_ID', :OLD.H_TAC_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_TAC_CLASS_ACID', :OLD.H_TAC_CLASS_ACID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_TAC_TIPO_ACID', :OLD.H_TAC_TIPO_ACID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.H_TAC_ID <> :OLD.H_TAC_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_TAC_ID', :OLD.H_TAC_ID, :NEW.H_TAC_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_TAC_CLASS_ACID <> :OLD.H_TAC_CLASS_ACID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_TAC_CLASS_ACID', :OLD.H_TAC_CLASS_ACID, :NEW.H_TAC_CLASS_ACID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_TAC_TIPO_ACID <> :OLD.H_TAC_TIPO_ACID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_TAC_TIPO_ACID', :OLD.H_TAC_TIPO_ACID, :NEW.H_TAC_TIPO_ACID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TRG_AUD_H_TIPOS_ACIDENTES" ENABLE;

--------------------------------------------------------
--  DDL for Trigger TRG_AUD_H_CONDICOES_CLIMATICAS
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_AUD_H_CONDICOES_CLIMATICAS" 
AFTER UPDATE OR DELETE ON APP.H_CONDICOES_CLIMATICAS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR2(20);
    V_TABELA VARCHAR2(30) := 'H_CONDICOES_CLIMATICAS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_CCM_ID', :OLD.H_CCM_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_CCM_METEORO', :OLD.H_CCM_METEORO, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_CCM_VISIB', :OLD.H_CCM_VISIB, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.H_CCM_ID <> :OLD.H_CCM_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_CCM_ID', :OLD.H_CCM_ID, :NEW.H_CCM_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_CCM_METEORO <> :OLD.H_CCM_METEORO) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_CCM_METEORO', :OLD.H_CCM_METEORO, :NEW.H_CCM_METEORO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_CCM_VISIB <> :OLD.H_CCM_VISIB) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_CCM_VISIB', :OLD.H_CCM_VISIB, :NEW.H_CCM_VISIB, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TRG_AUD_H_CONDICOES_CLIMATICAS" ENABLE;

--------------------------------------------------------
--  DDL for Trigger TRG_AUD_H_TIPOS_VEICULOS
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_AUD_H_TIPOS_VEICULOS" 
AFTER UPDATE OR DELETE ON APP.H_TIPOS_VEICULOS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR2(20);
    V_TABELA VARCHAR2(30) := 'H_TIPOS_VEICULOS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_TVC_ID', :OLD.H_TVC_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_TVC_VEICULO', :OLD.H_TVC_VEICULO, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.H_TVC_ID <> :OLD.H_TVC_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_TVC_ID', :OLD.H_TVC_ID, :NEW.H_TVC_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_TVC_VEICULO <> :OLD.H_TVC_VEICULO) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_TVC_VEICULO', :OLD.H_TVC_VEICULO, :NEW.H_TVC_VEICULO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TRG_AUD_H_TIPOS_VEICULOS" ENABLE;

--------------------------------------------------------
--  DDL for Trigger TRG_AUD_H_ACIDENTES
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_AUD_H_ACIDENTES" 
AFTER UPDATE OR DELETE ON APP.H_ACIDENTES
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR2(20);
    V_TABELA VARCHAR2(30) := 'H_ACIDENTES';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_ID', :OLD.H_ACD_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_MARCO_QM', :OLD.H_ACD_MARCO_QM, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_SENTIDO', :OLD.H_ACD_SENTIDO, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_DTHR_OC', :OLD.H_ACD_DTHR_OC, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_ANO', :OLD.H_ACD_ANO, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_MES', :OLD.H_ACD_MES, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_ILESA_INT', :OLD.H_ACD_ILESA_INT, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_VIT_FATAL_INT', :OLD.H_ACD_VIT_FATAL_INT, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_VIT_GRAVE_INT', :OLD.H_ACD_VIT_GRAVE_INT, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_VIT_LEVE_INT', :OLD.H_ACD_VIT_LEVE_INT, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_VIT_MODERADA_INT', :OLD.H_ACD_VIT_MODERADA_INT, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_VIT_SEMINFO_INT', :OLD.H_ACD_VIT_SEMINFO_INT, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_TIPO_PISTA', :OLD.H_ACD_TIPO_PISTA, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_LAT_FINAL', :OLD.H_ACD_LAT_FINAL, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_LON_FINAL', :OLD.H_ACD_LON_FINAL, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_ROD_ID', :OLD.H_ACD_ROD_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_TAC_ID', :OLD.H_ACD_TAC_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_CCM_ID', :OLD.H_ACD_CCM_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_MUN_ID', :OLD.H_ACD_MUN_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.H_ACD_ID <> :OLD.H_ACD_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_ID', :OLD.H_ACD_ID, :NEW.H_ACD_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_MARCO_QM <> :OLD.H_ACD_MARCO_QM) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_MARCO_QM', :OLD.H_ACD_MARCO_QM, :NEW.H_ACD_MARCO_QM, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_SENTIDO <> :OLD.H_ACD_SENTIDO) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_SENTIDO', :OLD.H_ACD_SENTIDO, :NEW.H_ACD_SENTIDO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_DTHR_OC <> :OLD.H_ACD_DTHR_OC) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_DTHR_OC', :OLD.H_ACD_DTHR_OC, :NEW.H_ACD_DTHR_OC, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_ANO <> :OLD.H_ACD_ANO) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_ANO', :OLD.H_ACD_ANO, :NEW.H_ACD_ANO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_MES <> :OLD.H_ACD_MES) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_MES', :OLD.H_ACD_MES, :NEW.H_ACD_MES, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_ILESA_INT <> :OLD.H_ACD_ILESA_INT) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_ILESA_INT', :OLD.H_ACD_ILESA_INT, :NEW.H_ACD_ILESA_INT, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_VIT_FATAL_INT <> :OLD.H_ACD_VIT_FATAL_INT) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_VIT_FATAL_INT', :OLD.H_ACD_VIT_FATAL_INT, :NEW.H_ACD_VIT_FATAL_INT, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_VIT_GRAVE_INT <> :OLD.H_ACD_VIT_GRAVE_INT) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_VIT_GRAVE_INT', :OLD.H_ACD_VIT_GRAVE_INT, :NEW.H_ACD_VIT_GRAVE_INT, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_VIT_LEVE_INT <> :OLD.H_ACD_VIT_LEVE_INT) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_VIT_LEVE_INT', :OLD.H_ACD_VIT_LEVE_INT, :NEW.H_ACD_VIT_LEVE_INT, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_VIT_MODERADA_INT <> :OLD.H_ACD_VIT_MODERADA_INT) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_VIT_MODERADA_INT', :OLD.H_ACD_VIT_MODERADA_INT, :NEW.H_ACD_VIT_MODERADA_INT, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_VIT_SEMINFO_INT <> :OLD.H_ACD_VIT_SEMINFO_INT) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_VIT_SEMINFO_INT', :OLD.H_ACD_VIT_SEMINFO_INT, :NEW.H_ACD_VIT_SEMINFO_INT, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_TIPO_PISTA <> :OLD.H_ACD_TIPO_PISTA) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_TIPO_PISTA', :OLD.H_ACD_TIPO_PISTA, :NEW.H_ACD_TIPO_PISTA, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_LAT_FINAL <> :OLD.H_ACD_LAT_FINAL) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_LAT_FINAL', :OLD.H_ACD_LAT_FINAL, :NEW.H_ACD_LAT_FINAL, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_LON_FINAL <> :OLD.H_ACD_LON_FINAL) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_LON_FINAL', :OLD.H_ACD_LON_FINAL, :NEW.H_ACD_LON_FINAL, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_ROD_ID <> :OLD.H_ACD_ROD_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_ROD_ID', :OLD.H_ACD_ROD_ID, :NEW.H_ACD_ROD_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_TAC_ID <> :OLD.H_ACD_TAC_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_TAC_ID', :OLD.H_ACD_TAC_ID, :NEW.H_ACD_TAC_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_CCM_ID <> :OLD.H_ACD_CCM_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_CCM_ID', :OLD.H_ACD_CCM_ID, :NEW.H_ACD_CCM_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_ACD_MUN_ID <> :OLD.H_ACD_MUN_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_ACD_MUN_ID', :OLD.H_ACD_MUN_ID, :NEW.H_ACD_MUN_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TRG_AUD_H_ACIDENTES" ENABLE;

--------------------------------------------------------
--  DDL for Trigger TRG_AUD_H_VEICULOS_ENVOLVIDOS
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_AUD_H_VEICULOS_ENVOLVIDOS" 
AFTER UPDATE OR DELETE ON APP.H_VEICULOS_ENVOLVIDOS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR2(30);
    V_USU_SO VARCHAR2(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR2(20);
    V_TABELA VARCHAR2(30) := 'H_VEICULOS_ENVOLVIDOS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_VEN_ID', :OLD.H_VEN_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_VEN_QTD', :OLD.H_VEN_QTD, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_VEN_ACD_ID', :OLD.H_VEN_ACD_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
        PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_VEN_TVC_ID', :OLD.H_VEN_TVC_ID, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.H_VEN_ID <> :OLD.H_VEN_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_VEN_ID', :OLD.H_VEN_ID, :NEW.H_VEN_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_VEN_QTD <> :OLD.H_VEN_QTD) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_VEN_QTD', :OLD.H_VEN_QTD, :NEW.H_VEN_QTD, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_VEN_ACD_ID <> :OLD.H_VEN_ACD_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_VEN_ACD_ID', :OLD.H_VEN_ACD_ID, :NEW.H_VEN_ACD_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.H_VEN_TVC_ID <> :OLD.H_VEN_TVC_ID) THEN
            PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'H_VEN_TVC_ID', :OLD.H_VEN_TVC_ID, :NEW.H_VEN_TVC_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TRG_AUD_H_VEICULOS_ENVOLVIDOS" ENABLE;