UPDATE ACIDENTES SET ACD_MARCO_QM = 999 WHERE ACD_ID = 102672;
UPDATE ACIDENTES SET ACD_SENTIDO = 'NORTE' WHERE ACD_ID = 102672;
UPDATE ACIDENTES SET ACD_VIT_FATAL_INT = 11 WHERE ACD_ID = 102672;

DELETE FROM VEICULOS_ENVOLVIDOS WHERE VEN_ACD_ID = 102673;
DELETE FROM ACIDENTES WHERE ACD_ID = 102673;

SELECT * FROM ACIDENTES WHERE ACD_ID = 102672;

SELECT * FROM H_VEICULOS_ENVOLVIDOS;
SELECT * FROM H_ACIDENTES;