ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER APP IDENTIFIED BY APP123 QUOTA UNLIMITED ON USERS;

GRANT connect,
resource TO APP;

ALTER TABLE DADOS ADD ID NUMBER(38);

UPDATE DADOS SET ID = SEQ_TEMP.NEXTVAL;