-- COMADOS PARA ZERAR O BANCO DE DADOS
DROP TABLE VEICULOS_ENVOLVIDOS;
DROP TABLE ACIDENTES;
DROP TABLE TIPOS_VEICULOS;
DROP TABLE TIPOS_ACIDENTES;
DROP TABLE RODOVIAS;
DROP TABLE CONCESSIONARIAS;
DROP TABLE CONDICOES_CLIMATICAS;
DROP TABLE MUNICIPIOS;
DROP TABLE DADOS;

DROP TABLE H_VEICULOS_ENVOLVIDOS;
DROP TABLE H_ACIDENTES;
DROP TABLE H_TIPOS_VEICULOS;
DROP TABLE H_TIPOS_ACIDENTES;
DROP TABLE H_RODOVIAS;
DROP TABLE H_CONCESSIONARIAS;
DROP TABLE H_CONDICOES_CLIMATICAS;
DROP TABLE H_MUNICIPIOS;

DROP SEQUENCE SEQ_MUNICIPIOS_ID;
DROP SEQUENCE SEQ_CONCESSIONARIAS_ID;
DROP SEQUENCE SEQ_RODOVIAS_ID;
DROP SEQUENCE SEQ_CONDICOES_CLIMATICAS_ID;
DROP SEQUENCE SEQ_TIPOS_ACIDENTES_ID;
DROP SEQUENCE SEQ_TIPOS_VEICULOS_ID;
DROP SEQUENCE SEQ_ACIDENTES_ID;
DROP SEQUENCE SEQ_VEICULOS_ENVOLVIDOS_ID;
DROP SEQUENCE SEQ_DADOS_ID;

DROP TRIGGER TRG_MUNICIPIOS;
DROP TRIGGER TRG_CONDICOES_CLIMATICAS;
DROP TRIGGER TRG_CONCESSIONARIAS;
DROP TRIGGER TRG_RODOVIAS;
DROP TRIGGER TRG_TIPOS_ACIDENTES;
DROP TRIGGER TRG_TIPOS_VEICULOS;
DROP TRIGGER TRG_ACIDENTES;
DROP TRIGGER TRG_VEICULOS_ENVOLVIDOS;

DROP TRIGGER TRG_MUNICIPIOS_INSERT;
DROP TRIGGER TRG_CONDICOES_CLIMATICAS_INSERT;
DROP TRIGGER TRG_CONCESSIONARIAS_INSERT;
DROP TRIGGER TRG_RODOVIAS_INSERT;
DROP TRIGGER TRG_TIPOS_ACIDENTES_INSERT;
DROP TRIGGER TRG_TIPOS_VEICULOS_INSERT;
DROP TRIGGER TRG_ACIDENTES_INSERT;
DROP TRIGGER TRG_VEICULOS_ENVOLVIDOS_INSERT;

DROP TRIGGER TG_AUD_H_CONCESSIONARIA;
DROP TRIGGER TG_AUD_H_RODOVIAS;
DROP TRIGGER TG_AUD_H_MUNICIPIOS;
DROP TRIGGER TG_AUD_H_TIPOS_ACIDENTES;
DROP TRIGGER TG_AUD_H_CONDICOES_CLIMATICAS;
DROP TRIGGER TG_AUD_H_TIPOS_VEICULOS;
DROP TRIGGER TG_AUD_H_ACIDENTES;
DROP TRIGGER TG_AUD_H_VEICULOS_ENVOLVIDOS;

-- SEQUENCES
-- ALTER SEQUENCE SEQ_DADOS_ID RESTART;
-- ALTER SEQUENCE SEQ_MUNICIPIOS_ID RESTART;
-- ALTER SEQUENCE SEQ_CONCESSIONARIAS_ID RESTART;
-- ALTER SEQUENCE SEQ_RODOVIAS_ID RESTART;
-- ALTER SEQUENCE SEQ_CONDICOES_CLIMATICAS_ID RESTART;
-- ALTER SEQUENCE SEQ_TIPOS_ACIDENTES_ID RESTART;
-- ALTER SEQUENCE SEQ_TIPOS_VEICULOS_ID RESTART;
-- ALTER SEQUENCE SEQ_ACIDENTES_ID RESTART;
-- ALTER SEQUENCE SEQ_VEICULOS_ENVOLVIDOS_ID RESTART;