-------------------------------------------------------------------------------
--                                                                           --
--  SEQUENCES                                                                --
--                                                                           --
--  CRIA AS SEQUENCES DE IDS PARA OS REGISTROS                               --
--                                                                           --
-------------------------------------------------------------------------------

CREATE SEQUENCE SEQ_DADOS_ID NOCACHE;
CREATE SEQUENCE SEQ_MUNICIPIOS_ID NOCACHE;
CREATE SEQUENCE SEQ_CONCESSIONARIAS_ID NOCACHE;
CREATE SEQUENCE SEQ_RODOVIAS_ID NOCACHE;
CREATE SEQUENCE SEQ_CONDICOES_CLIMATICAS_ID NOCACHE;
CREATE SEQUENCE SEQ_TIPOS_ACIDENTES_ID NOCACHE;
CREATE SEQUENCE SEQ_TIPOS_VEICULOS_ID NOCACHE;
CREATE SEQUENCE SEQ_ACIDENTES_ID NOCACHE;
CREATE SEQUENCE SEQ_VEICULOS_ENVOLVIDOS_ID NOCACHE;

--------------------------------------------------------------------------------
--                                                                            --
--  TABELAS                                                                   --
--                                                                            --
--  SCRIPTS PARA CRIAR OS SCHEMAS DAS TABELAS                                 --
--                                                                            --
--------------------------------------------------------------------------------

CREATE TABLE MUNICIPIOS (
    MUN_ID NUMBER (38), 
    MUN_MUNICIPIO VARCHAR(100) NOT NULL,
    MUN_REG_DER VARCHAR(100) NOT NULL,
    MUN_REG_ADM VARCHAR(100) NOT NULL
);

CREATE TABLE CONDICOES_CLIMATICAS (
    CCM_ID NUMBER(38), 
    CCM_METEORO VARCHAR(100) NOT NULL,
    CCM_VISIB VARCHAR(100) NOT NULL
);

CREATE TABLE CONCESSIONARIAS (
    CON_ID NUMBER (38), 
    CON_CONCESSIONARIA VARCHAR(100) NOT NULL
);

CREATE TABLE RODOVIAS (
    ROD_ID NUMBER(38), 
    ROD_CODIGO_RODOVIA VARCHAR(100) NOT NULL,
    ROD_DENOMINACAO VARCHAR(100),
    ROD_JURISDICAO VARCHAR(100),
    ROD_CON_ID NUMBER(38) NOT NULL
);

CREATE TABLE TIPOS_ACIDENTES (
    TAC_ID NUMBER(38), 
    TAC_CLASS_ACID VARCHAR(100),
    TAC_TIPO_ACID VARCHAR(100)
);

CREATE TABLE TIPOS_VEICULOS (
    TVC_ID NUMBER (38), 
    TVC_VEICULO VARCHAR(100)
);

CREATE TABLE ACIDENTES (
    ACD_ID NUMBER(38),
    ACD_MARCO_QM NUMBER(38) NOT NULL,
    ACD_SENTIDO VARCHAR(100) NOT NULL,
    ACD_DTHR_OC DATE NOT NULL,
    ACD_ANO NUMBER(38) NOT NULL,
    ACD_MES NUMBER(38) NOT NULL,
    ACD_ILESA_INT NUMBER(38) NOT NULL,
    ACD_VIT_FATAL_INT NUMBER(38) NOT NULL,
    ACD_VIT_GRAVE_INT NUMBER(38) NOT NULL,
    ACD_VIT_LEVE_INT NUMBER(38) NOT NULL,
    ACD_VIT_MODERADA_INT NUMBER(38) NOT NULL,
    ACD_VIT_SEMINFO_INT NUMBER(38) NOT NULL,
    ACD_TIPO_PISTA VARCHAR(100) NOT NULL,
    ACD_LAT_FINAL NUMBER(38) NOT NULL,
    ACD_LON_FINAL NUMBER(38) NOT NULL,
    ACD_ROD_ID NUMBER(38) NOT NULL,
    ACD_TAC_ID NUMBER(38) NOT NULL,
    ACD_CCM_ID NUMBER(38) NOT NULL,
    ACD_MUN_ID NUMBER(38)
);

CREATE TABLE VEICULOS_ENVOLVIDOS (
    VEN_ID NUMBER(38),
    VEN_QTD NUMBER(38) NOT NULL,
    VEN_ACD_ID NUMBER(38) NOT NULL,
    VEN_TVC_ID NUMBER(38) NOT NULL
);

--------------------------------------------------------------------------------
--                                                                            --
--  CONTRAINTS                                                                --
--                                                                            --
--  SCRIPTS PARA CRIAR AS CONTRAINTS DAS ENTIDADES                            --
--                                                                            --
--------------------------------------------------------------------------------

-- CRIAÇÃO DAS CONTRAINTS: MUNICIPIOS
ALTER TABLE MUNICIPIOS
ADD CONSTRAINT PK_MUNICIPIOS UNIQUE (MUN_ID);

ALTER TABLE MUNICIPIOS
ADD CONSTRAINT UQ_MUNICIPIOS UNIQUE (MUN_MUNICIPIO, MUN_REG_ADM, MUN_REG_DER);


-- CRIAÇÃO DAS CONTRAINTS: CONDICOES CLIMATICAS
ALTER TABLE CONDICOES_CLIMATICAS
ADD CONSTRAINT PK_CONDICOES_CLIMATICAS PRIMARY KEY (CCM_ID);

ALTER TABLE CONDICOES_CLIMATICAS
ADD CONSTRAINT UQ_CONDICOES_CLIMATICAS UNIQUE (CCM_METEORO, CCM_VISIB);


-- CRIAÇÃO DAS CONTRAINTS: CONCESSIONARIAS
ALTER TABLE CONCESSIONARIAS
ADD CONSTRAINT PK_CONCESSIONARIAS PRIMARY KEY (CON_ID);

ALTER TABLE CONCESSIONARIAS
ADD CONSTRAINT UQ_CONCESSIONARIAS UNIQUE (CON_CONCESSIONARIA);


-- CRIAÇÃO DAS CONTRAINTS: RODOVIAS
ALTER TABLE RODOVIAS
ADD CONSTRAINT PK_RODOVIAS PRIMARY KEY (ROD_ID);

ALTER TABLE RODOVIAS
ADD CONSTRAINT UQ_RODOVIAS UNIQUE (ROD_CODIGO_RODOVIA, ROD_DENOMINACAO, ROD_JURISDICAO, ROD_CON_ID);

ALTER TABLE RODOVIAS
ADD CONSTRAINT FK_RODOVIAS_CONCESSIONARIAS FOREIGN KEY (ROD_CON_ID)
    REFERENCES CONCESSIONARIAS(CON_ID);


-- CRIAÇÃO DAS CONTRAINTS: TIPOS_ACIDENTES
ALTER TABLE TIPOS_ACIDENTES
ADD CONSTRAINT PK_TIPOS_ACIDENTES PRIMARY KEY (TAC_ID);

ALTER TABLE TIPOS_ACIDENTES
ADD CONSTRAINT UQ_TIPOS_ACIDENTES UNIQUE (TAC_CLASS_ACID, TAC_TIPO_ACID);


-- CRIAÇÃO DAS CONTRAINTS: TIPOS_VEICULOS
ALTER TABLE TIPOS_VEICULOS
ADD CONSTRAINT PK_TIPOS_VEICULOS PRIMARY KEY (TVC_ID);

ALTER TABLE TIPOS_VEICULOS
ADD CONSTRAINT UQ_TIPOS_VEICULOS UNIQUE (TVC_VEICULO);


-- CRIAÇÃO DAS CONTRAINTS: ACIDENTES
ALTER TABLE ACIDENTES
ADD CONSTRAINT PK_ACIDENTES PRIMARY KEY (ACD_ID);

ALTER TABLE ACIDENTES
ADD CONSTRAINT FK_ACIDENTES_RODOVIAS FOREIGN KEY(ACD_ROD_ID) REFERENCES RODOVIAS(ROD_ID);

ALTER TABLE ACIDENTES
ADD CONSTRAINT FK_ACIDENTES_TIPOS_ACIDENTES FOREIGN KEY(ACD_TAC_ID) REFERENCES TIPOS_ACIDENTES(TAC_ID);

ALTER TABLE ACIDENTES
ADD CONSTRAINT FK_ACIDENTES_CONDICOES_CLIMATICAS FOREIGN KEY(ACD_CCM_ID) REFERENCES CONDICOES_CLIMATICAS(CCM_ID);

ALTER TABLE ACIDENTES
ADD CONSTRAINT FK_ACIDENTES_MUNICIPIOS FOREIGN KEY(ACD_MUN_ID) REFERENCES MUNICIPIOS(MUN_ID);


-- CRIAÇÃO DAS CONTRAINTS: VEICULOS_ENVOLVIDOS
ALTER TABLE VEICULOS_ENVOLVIDOS
ADD CONSTRAINT PK_VEICULOS_ENVOLVIDOS PRIMARY KEY (VEN_ID);

ALTER TABLE VEICULOS_ENVOLVIDOS
ADD CONSTRAINT FK_VEICULOS_ENVOLVIDOS_ACIDENTES FOREIGN KEY(VEN_ACD_ID) REFERENCES ACIDENTES(ACD_ID);

ALTER TABLE VEICULOS_ENVOLVIDOS
ADD CONSTRAINT FK_VEICULOS_ENVOLVIDOS_TIPOS_VEICULOS FOREIGN KEY(VEN_TVC_ID) REFERENCES TIPOS_VEICULOS(TVC_ID);

--------------------------------------------------------------------------------
--                                                                            --
--  HISTORIAMENTO                                                             --
--                                                                            --
--  SCRIPTS PARA CRIAR AS ENTIDADES DE HISTORIAMENTO                          --
--                                                                            --
--------------------------------------------------------------------------------
CREATE TABLE H_MUNICIPIOS (
    OLD_MUN_ID NUMBER (38),
    OLD_MUN_MUNICIPIO VARCHAR(100),
    OLD_MUN_REG_DER VARCHAR(100),
    OLD_MUN_REG_ADM VARCHAR(100),
    OLD_MUN_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(OLD_MUN_ID, OLD_MUN_CREATED_AT)
);


CREATE TABLE H_CONDICOES_CLIMATICAS (
    OLD_CCM_ID NUMBER (38), 
    OLD_CCM_METEORO VARCHAR(100),
    OLD_CCM_VISIB VARCHAR(100),
    OLD_CCM_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(OLD_CCM_ID, OLD_CCM_CREATED_AT)
);

CREATE TABLE H_CONCESSIONARIAS (
    OLD_CON_ID NUMBER (38), 
    OLD_CON_CONCESSIONARIA VARCHAR(100),
    OLD_CON_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(OLD_CON_ID, OLD_CON_CREATED_AT)
);

CREATE TABLE H_RODOVIAS (
    OLD_ROD_ID NUMBER (38), 
    OLD_ROD_CODIGO_RODOVIA VARCHAR(100),
    OLD_ROD_DENOMINACAO VARCHAR(100),
    OLD_ROD_JURISDICAO VARCHAR(100),
    OLD_ROD_CON_ID NUMBER(38),
    OLD_ROD_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(OLD_ROD_ID, OLD_ROD_CREATED_AT)
);

CREATE TABLE H_TIPOS_ACIDENTES (
    OLD_TAC_ID NUMBER (38), 
    OLD_TAC_CLASS_ACID VARCHAR(100),
    OLD_TAC_TIPO_ACID VARCHAR(100),
    OLD_TAC_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(OLD_TAC_ID, OLD_TAC_CREATED_AT)
);

CREATE TABLE H_TIPOS_VEICULOS (
    OLD_TVC_ID NUMBER (38), 
    OLD_TVC_VEICULO VARCHAR(100),
    OLD_TVC_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(OLD_TVC_ID, OLD_TVC_CREATED_AT)
);

CREATE TABLE H_ACIDENTES (
    OLD_ACD_ID NUMBER(38),
    OLD_ACD_MARCO_QM NUMBER(38),
    OLD_ACD_SENTIDO VARCHAR(100),
    OLD_ACD_DTHR_OC DATE,
    OLD_ACD_ANO NUMBER(38),
    OLD_ACD_MES NUMBER(38),
    OLD_ACD_ILESA_INT NUMBER(38),
    OLD_ACD_VIT_FATAL_INT NUMBER(38),
    OLD_ACD_VIT_GRAVE_INT NUMBER(38),
    OLD_ACD_VIT_LEVE_INT NUMBER(38),
    OLD_ACD_VIT_MODERADA_INT NUMBER(38),
    OLD_ACD_VIT_SEMINFO_INT NUMBER(38),
    OLD_ACD_TIPO_PISTA VARCHAR(100),
    OLD_ACD_LAT_FINAL NUMBER(38),
    OLD_ACD_LON_FINAL NUMBER(38),
    OLD_ACD_ROD_ID NUMBER(38),
    OLD_ACD_TAC_ID NUMBER(38),
    OLD_ACD_CCM_ID NUMBER(38),
    OLD_ACD_MUN_ID NUMBER(38),
    OLD_ACD_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(OLD_ACD_ID, OLD_ACD_CREATED_AT)
);

CREATE TABLE H_VEICULOS_ENVOLVIDOS (
    OLD_VEN_ID NUMBER(38),
    OLD_VEN_QTD NUMBER(38),
    OLD_VEN_ACD_ID NUMBER(38),
    OLD_VEN_TVC_ID NUMBER(38),
    OLD_VEN_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(OLD_VEN_ID, OLD_VEN_CREATED_AT)
);

--------------------------------------------------------------------------------
--                                                                            --
--  TRIGGERS                                                                  --
--                                                                            --
--  SCRIPTS PARA CRIAR AS TRIGGERS QUE EXECUTAM O HISTORIAMENTO               --
--                                                                            --
--------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_MUNICIPIOS
AFTER DELETE OR UPDATE ON MUNICIPIOS
FOR EACH ROW
BEGIN
    INSERT INTO H_MUNICIPIOS(OLD_MUN_ID, OLD_MUN_MUNICIPIO, OLD_MUN_REG_DER, OLD_MUN_REG_ADM) VALUES (
        :OLD.MUN_ID, 
        :OLD.MUN_MUNICIPIO, 
        :OLD.MUN_REG_DER, 
        :OLD.MUN_REG_ADM);
END;
/

CREATE OR REPLACE TRIGGER TRG_CONDICOES_CLIMATICAS
AFTER DELETE OR UPDATE ON CONDICOES_CLIMATICAS
FOR EACH ROW
BEGIN
    INSERT INTO H_CONDICOES_CLIMATICAS(OLD_CCM_ID, OLD_CCM_METEORO, OLD_CCM_VISIB) 
    VALUES (:OLD.CCM_ID, :OLD.CCM_METEORO, :OLD.CCM_VISIB);
END;
/

CREATE OR REPLACE TRIGGER TRG_CONCESSIONARIAS
AFTER DELETE OR UPDATE ON CONCESSIONARIAS
FOR EACH ROW
BEGIN
    INSERT INTO H_CONCESSIONARIAS (OLD_CON_ID, OLD_CON_CONCESSIONARIA)
    VALUES (:OLD.CON_ID, :OLD.CON_CONCESSIONARIA);
END;
/

CREATE OR REPLACE TRIGGER TRG_RODOVIAS
AFTER DELETE OR UPDATE ON RODOVIAS
FOR EACH ROW
BEGIN
    INSERT INTO H_RODOVIAS(
        OLD_ROD_ID, 
        OLD_ROD_CODIGO_RODOVIA, 
        OLD_ROD_DENOMINACAO, 
        OLD_ROD_JURISDICAO, 
        OLD_ROD_CON_ID)
    VALUES (
        :OLD.ROD_ID, 
        :OLD.ROD_CODIGO_RODOVIA,
        :OLD.ROD_DENOMINACAO,
        :OLD.ROD_JURISDICAO,
        :OLD.ROD_CON_ID
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_TIPOS_ACIDENTES
AFTER DELETE OR UPDATE ON TIPOS_ACIDENTES
FOR EACH ROW
BEGIN
    INSERT INTO H_TIPOS_ACIDENTES(
        OLD_TAC_ID, 
        OLD_TAC_CLASS_ACID, 
        OLD_TAC_TIPO_ACID)
     VALUES (
        :OLD.TAC_ID, 
        :OLD.TAC_CLASS_ACID,
        :OLD.TAC_TIPO_ACID
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_TIPOS_VEICULOS
AFTER DELETE OR UPDATE ON TIPOS_VEICULOS
FOR EACH ROW
BEGIN
    INSERT INTO H_TIPOS_VEICULOS(OLD_TVC_ID, OLD_TVC_VEICULO) 
    VALUES (:OLD.TVC_ID, :OLD.TVC_VEICULO);
END;
/

CREATE OR REPLACE TRIGGER TRG_ACIDENTES
AFTER DELETE OR UPDATE ON ACIDENTES
FOR EACH ROW
BEGIN
    INSERT INTO H_ACIDENTES(
        OLD_ACD_ID,
        OLD_ACD_MARCO_QM,
        OLD_ACD_SENTIDO,
        OLD_ACD_DTHR_OC,
        OLD_ACD_ANO,
        OLD_ACD_MES,
        OLD_ACD_ILESA_INT,
        OLD_ACD_VIT_FATAL_INT,
        OLD_ACD_VIT_GRAVE_INT,
        OLD_ACD_VIT_LEVE_INT,
        OLD_ACD_VIT_MODERADA_INT,
        OLD_ACD_VIT_SEMINFO_INT,
        OLD_ACD_TIPO_PISTA,
        OLD_ACD_LAT_FINAL,
        OLD_ACD_LON_FINAL,
        OLD_ACD_ROD_ID,
        OLD_ACD_TAC_ID,
        OLD_ACD_CCM_ID,
        OLD_ACD_MUN_ID
    ) 
    VALUES (
        :OLD.ACD_ID,
        :OLD.ACD_MARCO_QM,
        :OLD.ACD_SENTIDO,
        :OLD.ACD_DTHR_OC,
        :OLD.ACD_ANO,
        :OLD.ACD_MES,
        :OLD.ACD_ILESA_INT,
        :OLD.ACD_VIT_FATAL_INT,
        :OLD.ACD_VIT_GRAVE_INT,
        :OLD.ACD_VIT_LEVE_INT,
        :OLD.ACD_VIT_MODERADA_INT,
        :OLD.ACD_VIT_SEMINFO_INT,
        :OLD.ACD_TIPO_PISTA,
        :OLD.ACD_LAT_FINAL,
        :OLD.ACD_LON_FINAL,
        :OLD.ACD_ROD_ID,
        :OLD.ACD_TAC_ID,
        :OLD.ACD_CCM_ID,
        :OLD.ACD_MUN_ID
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_VEICULOS_ENVOLVIDOS
AFTER DELETE OR UPDATE ON VEICULOS_ENVOLVIDOS
FOR EACH ROW
BEGIN
    INSERT INTO H_VEICULOS_ENVOLVIDOS(
        OLD_VEN_ID,
        OLD_VEN_QTD,
        OLD_VEN_ACD_ID,
        OLD_VEN_TVC_ID
    ) 
    VALUES (
        :OLD.VEN_ID,
        :OLD.VEN_QTD,
        :OLD.VEN_ACD_ID,
        :OLD.VEN_TVC_ID
    );
END;
/
