-- DROP TABLE VEICULOS_ENVOLVIDOS;
-- DROP TABLE ACIDENTES;
-- DROP TABLE TIPOS_VEICULOS;
-- DROP TABLE TIPOS_ACIDENTES;
-- DROP TABLE RODOVIAS;
-- DROP TABLE CONCESSIONARIAS;
-- DROP TABLE CONDICOES_CLIMATICAS;
-- DROP TABLE MUNICIPIOS;

CREATE TABLE MUNICIPIOS (
    MUN_ID NUMBER (38), 
    MUN_MUNICIPIO VARCHAR(100) NOT NULL,
    MUN_REG_DER VARCHAR(100) NOT NULL,
    MUN_REG_ADM VARCHAR(100) NOT NULL,
    PRIMARY KEY (MUN_ID)
);

CREATE TABLE CONDICOES_CLIMATICAS (
    CCM_ID NUMBER(38), 
    CCM_METEORO VARCHAR(100) NOT NULL,
    CCM_VISIB VARCHAR(100) NOT NULL,
    PRIMARY KEY (CCM_ID)
);

CREATE TABLE CONCESSIONARIAS (
    CON_ID NUMBER (38), 
    CON_CONCESSIONARIA VARCHAR(100) NOT NULL,
    PRIMARY KEY (CON_ID)
);

CREATE TABLE RODOVIAS (
    ROD_ID NUMBER(38), 
    ROD_CODIGO_RODOVIA VARCHAR(100) NOT NULL,
    ROD_DENOMINACAO VARCHAR(100),
    ROD_JURISDICAO VARCHAR(100),
    ROD_CON_ID NUMBER(38) NOT NULL,
    PRIMARY KEY(ROD_ID),
    FOREIGN KEY(ROD_CON_ID) REFERENCES CONCESSIONARIAS(CON_ID)
);

CREATE TABLE TIPOS_ACIDENTES (
    TAC_ID NUMBER(38), 
    TAC_CLASS_ACID VARCHAR(100),
    TAC_TIPO_ACID VARCHAR(100),
    PRIMARY KEY(TAC_ID)
);

CREATE TABLE TIPOS_VEICULOS (
    TVC_ID NUMBER (38), 
    TVC_VEICULO VARCHAR(100),
    PRIMARY KEY(TVC_ID)
);

CREATE TABLE ACIDENTES (
    ACD_ID NUMBER(38),
    ACD_MARCO_QM NUMBER(38) NOT NULL,
    ACD_SENTIDO VARCHAR(100) NOT NULL,
    ACD_DTHR_OC DATE NOT NULL,
    ACD_ANO NUMBER(38) NOT NULL,
    ACD_MES NUMBER(38) NOT NULL,
    ACD_ILESA_INT NUMBER(38) NOT NULL,
    ACD_VIT_FATAL_INT NUMBER(38) NOT NULL,
    ACD_VIT_GRAVE_INT NUMBER(38) NOT NULL,
    ACD_VIT_LEVE_INT NUMBER(38) NOT NULL,
    ACD_VIT_MODERADA_INT NUMBER(38) NOT NULL,
    ACD_VIT_SEMINFO_INT NUMBER(38) NOT NULL,
    ACD_TIPO_PISTA VARCHAR(100) NOT NULL,
    ACD_LAT_FINAL NUMBER(38) NOT NULL,
    ACD_LON_FINAL NUMBER(38) NOT NULL,
    ACD_ROD_ID NUMBER(38) NOT NULL,
    ACD_TAC_ID NUMBER(38) NOT NULL,
    ACD_CCM_ID NUMBER(38) NOT NULL,
    ACD_MUN_ID NUMBER(38),
    PRIMARY KEY(ACD_ID),
    FOREIGN KEY(ACD_ROD_ID) REFERENCES RODOVIAS(ROD_ID),
    FOREIGN KEY(ACD_TAC_ID) REFERENCES TIPOS_ACIDENTES(TAC_ID),
    FOREIGN KEY(ACD_CCM_ID) REFERENCES CONDICOES_CLIMATICAS(CCM_ID),
    FOREIGN KEY(ACD_MUN_ID) REFERENCES MUNICIPIOS(MUN_ID)
);

CREATE TABLE VEICULOS_ENVOLVIDOS (
    VEN_ID NUMBER(38),
    VEN_QTD NUMBER(38) NOT NULL,
    VEN_ACD_ID NUMBER(38) NOT NULL,
    VEN_TVC_ID NUMBER(38) NOT NULL,
    PRIMARY KEY(VEN_ID),
    FOREIGN KEY(VEN_ACD_ID) REFERENCES ACIDENTES(ACD_ID),
    FOREIGN KEY(VEN_TVC_ID) REFERENCES TIPOS_VEICULOS(TVC_ID)
);
