-- DROP TABLE H_VEICULOS_ENVOLVIDOS;
-- DROP TABLE H_ACIDENTES;
-- DROP TABLE H_TIPOS_VEICULOS;
-- DROP TABLE H_TIPOS_ACIDENTES;
-- DROP TABLE H_RODOVIAS;
-- DROP TABLE H_CONCESSIONARIAS;
-- DROP TABLE H_CONDICOES_CLIMATICAS;
-- DROP TABLE H_MUNICIPIOS;

CREATE TABLE H_MUNICIPIOS (
    OLD_MUN_ID NUMBER (38), 
    OLD_MUN_MUNICIPIO VARCHAR(100),
    OLD_MUN_REG_DER VARCHAR(100),
    OLD_MUN_REG_ADM VARCHAR(100)
);

CREATE TABLE H_CONDICOES_CLIMATICAS (
    OLD_CCM_ID NUMBER (38), 
    OLD_CCM_METEORO VARCHAR(100),
    OLD_CCM_VISIB VARCHAR(100)
);

CREATE TABLE H_CONCESSIONARIAS (
    OLD_CON_ID NUMBER (38), 
    OLD_CON_CONCESSIONARIA VARCHAR(100)
);

CREATE TABLE H_RODOVIAS (
    OLD_ROD_ID NUMBER (38), 
    OLD_ROD_RODOVIAS VARCHAR(100),
    OLD_ROD_DENOMINACAO VARCHAR(100),
    OLD_ROD_JURISDICAO VARCHAR(100),
    OLD_ROD_CON_ID VARCHAR(100)
);

CREATE TABLE H_TIPOS_ACIDENTES (
    OLD_TAC_ID NUMBER (38), 
    OLD_TAC_CLASS_ACID VARCHAR(100),
    OLD_TAC_TIPO_ACID VARCHAR(100)
);

CREATE TABLE H_TIPOS_VEICULOS (
    OLD_TVC_ID NUMBER (38), 
    OLD_TVC_VEICULO VARCHAR(100)
);

CREATE TABLE H_ACIDENTES (
    OLD_ACD_ID NUMBER(38),
    OLD_ACD_MARCO_QM NUMBER(38),
    OLD_ACD_SENTIDO VARCHAR(100),
    OLD_ACD_DTHR_OC DATE,
    OLD_ACD_ANO NUMBER(38),
    OLD_ACD_MES NUMBER(38),
    OLD_ACD_ILESA_INT NUMBER(38),
    OLD_ACD_VIT_FATAL_INT NUMBER(38),
    OLD_ACD_VIT_GRAVE_INT NUMBER(38),
    OLD_ACD_VIT_LEVE_INT NUMBER(38),
    OLD_ACD_VIT_MODERADA_INT NUMBER(38),
    OLD_ACD_VIT_SEMINFO_INT NUMBER(38),
    OLD_ACD_TIPO_VISTA VARCHAR(100),
    OLD_ACD_LAT_FINAL NUMBER(38),
    OLD_ACD_LON_FINAL NUMBER(38),
    OLD_ACD_ROD_ID NUMBER(38),
    OLD_ACD_TAC_ID NUMBER(38),
    OLD_ACD_CCM_ID NUMBER(38),
    OLD_ACD_MUN_ID NUMBER(38)
);

CREATE TABLE H_VEICULOS_ENVOLVIDOS (
    OLD_VEN_ID NUMBER(38),
    OLD_VEN_QTD NUMBER(38),
    OLD_VEN_ACD_ID NUMBER(38),
    OLD_VEN_TVC_ID NUMBER(38)
);
