CREATE OR REPLACE TRIGGER TRG_MUNICIPIOS
AFTER DELETE OR UPDATE ON MUNICIPIOS
FOR EACH ROW
BEGIN
    INSERT INTO H_MUNICIPIOS VALUES (
        :OLD.OLD_MUN_ID, 
        :OLD.OLD_MUN_MUNICIPIO, 
        :OLD.OLD_MUN_REG_DER, 
        :OLD.OLD_MUN_REG_ADM)
END;

CREATE OR REPLACE TRIGGER TRG_CONDICOES_CLIMATICAS
AFTER DELETE OR UPDATE ON CONDICOES_CLIMATICAS
FOR EACH ROW
BEGIN
    INSERT INTO H_CONDICOES_CLIMATICAS VALUES (
        :OLD.OLD_CCM_ID, 
        :OLD.OLD_CCM_METEORO, 
        :OLD.OLD_CCM_VISIB
    )
END;

CREATE OR REPLACE TRIGGER TRG_CONCESSIONARIAS
AFTER DELETE OR UPDATE ON CONCESSIONARIAS
FOR EACH ROW
BEGIN
    INSERT INTO H_CONCESSIONARIAS VALUES (
        :OLD.OLD_CON_ID, 
        :OLD.OLD_CON_CONCESSIONARIA
    )
END;

CREATE OR REPLACE TRIGGER TRG_RODOVIAS
AFTER DELETE OR UPDATE ON RODOVIAS
FOR EACH ROW
BEGIN
    INSERT INTO H_RODOVIAS VALUES (
        :OLD.OLD_ROD_ID, 
        :OLD.OLD_ROD_RODOVIAS,
        :OLD.OLD_ROD_DENOMINACAO,
        :OLD.OLD_ROD_JURISDICAO,
        :OLD.OLD_ROD_CON_ID
    )
END;

CREATE OR REPLACE TRIGGER TRG_TIPOS_ACIDENTES
AFTER DELETE OR UPDATE ON TIPOS_ACIDENTES
FOR EACH ROW
BEGIN
    INSERT INTO H_TIPOS_ACIDENTES VALUES (
        :OLD.OLD_TAC_ID, 
        :OLD.OLD_TAC_CLASS_ACID,
        :OLD.OLD_TAC_TIPO_ACID
    )
END;

CREATE OR REPLACE TRIGGER TRG_TIPOS_VEICULOS
AFTER DELETE OR UPDATE ON TIPOS_VEICULOS
FOR EACH ROW
BEGIN
    INSERT INTO H_TIPOS_VEICULOS VALUES (
        :OLD.OLD_TVC_ID, 
        :OLD.OLD_TVC_VEICULO
    )
END;

CREATE OR REPLACE TRIGGER TRG_ACIDENTES
AFTER DELETE OR UPDATE ON ACIDENTES
FOR EACH ROW
BEGIN
    INSERT INTO H_ACIDENTES VALUES (
        :OLD.OLD_ACD_ID,
        :OLD.OLD_ACD_MARCO_QM,
        :OLD.OLD_ACD_SENTIDO,
        :OLD.OLD_ACD_DTHR_OC,
        :OLD.OLD_ACD_ANO,
        :OLD.OLD_ACD_MES,
        :OLD.OLD_ACD_ILESA_INT,
        :OLD.OLD_ACD_VIT_FATAL_INT,
        :OLD.OLD_ACD_VIT_GRAVE_INT,
        :OLD.OLD_ACD_VIT_LEVE_INT,
        :OLD.OLD_ACD_VIT_MODERADA_INT,
        :OLD.OLD_ACD_VIT_SEMINFO_INT,
        :OLD.OLD_ACD_TIPO_VISTA,
        :OLD.OLD_ACD_LAT_FINAL,
        :OLD.OLD_ACD_LON_FINAL,
        :OLD.OLD_ACD_ROD_ID,
        :OLD.OLD_ACD_TAC_ID,
        :OLD.OLD_ACD_CCM_ID,
        :OLD.OLD_ACD_MUN_ID,
    )
END;

CREATE OR REPLACE TRIGGER TRG_VEICULOS_ENVOLVIDOS
AFTER DELETE OR UPDATE ON VEICULOS_ENVOLVIDOS
FOR EACH ROW
BEGIN
    INSERT INTO H_VEICULOS_ENVOLVIDOS VALUES (
        :OLD.OLD_VEN_ID,
        :OLD.OLD_VEN_QTD,
        :OLD.OLD_VEN_ACD_ID,
        :OLD.OLD_VEN_TVC_ID
    )
END;