-- SEQUENCES
CREATE SEQUENCE SEQ_MUNICIPIOS_ID NOCACHE;
CREATE SEQUENCE SEQ_CONCESSIONARIAS_ID NOCACHE;
CREATE SEQUENCE SEQ_RODOVIAS_ID NOCACHE;
CREATE SEQUENCE SEQ_CONDICOES_CLIMATICAS_ID NOCACHE;
CREATE SEQUENCE SEQ_TIPOS_ACIDENTES_ID NOCACHE;
CREATE SEQUENCE SEQ_TIPOS_VEICULOS_ID NOCACHE;
CREATE SEQUENCE SEQ_ACIDENTES_ID NOCACHE;
CREATE SEQUENCE SEQ_VEICULOS_ENVOLVIDOS_ID NOCACHE;

-- CONFIGURAÇÃO DA TABELA DE DADOS PARA MELHORAR CONSULTAS
ALTER TABLE DADOS ADD ID NUMBER(38);
UPDATE DADOS SET ID = SEQ_TEMP.NEXTVAL;

-- Insert dos MUNCIPIOS
INSERT INTO 
    MUNICIPIOS(MUN_ID, MUN_MUNICIPIO, MUN_REG_DER, MUN_REG_ADM)
SELECT 
    SEQ_MUNICIPIOS_ID.NEXTVAL AS MUN_ID,
    DADOS_2.MUNICÍPIO,
    DADOS_2.REGIONAL_DER,
    DADOS_2.REG_ADM_SP
FROM     
    (SELECT DISTINCT            
        MUNICÍPIO,
        REGIONAL_DER,
        REG_ADM_SP
    FROM DADOS
    WHERE MUNICÍPIO IS NOT NULL) DADOS_2;

-- Insert dos CONCESSIONARIAS
INSERT INTO 
    CONCESSIONARIAS(CON_ID, CON_CONCESSIONARIA)
SELECT 
    SEQ_CONCESSIONARIAS_ID.NEXTVAL AS CON_ID,
    DADOS_2.NOME_CONC
FROM     
    (SELECT DISTINCT            
        NOME_CONC
    FROM DADOS
    WHERE NOME_CONC IS NOT NULL) DADOS_2;

-- Insert dos RODOVIAS
INSERT INTO 
    RODOVIAS(ROD_ID, ROD_CODIGO_RODOVIA, ROD_DENOMINACAO, ROD_JURISDICAO, ROD_CON_ID)
SELECT 
    SEQ_RODOVIAS_ID.NEXTVAL AS CON_ID,
    DADOS_2.RODOVIA,
    DADOS_2.DENOMINACAO,
    DADOS_2.JURISDICAO,
    DADOS_2.CON_ID
FROM     
    (SELECT DISTINCT            
        D.RODOVIA,
        D.DENOMINACAO,
        D.JURISDICAO,
        C.CON_ID
    FROM DADOS D
    JOIN CONCESSIONARIAS C ON D.NOME_CONC = C.CON_CONCESSIONARIA
    ) DADOS_2;

-- Insert dos CONDICOES_CLIMATICAS
INSERT INTO 
    CONDICOES_CLIMATICAS(CCM_ID, CCM_METEORO, CCM_VISIB)
SELECT 
    SEQ_CONDICOES_CLIMATICAS_ID.NEXTVAL AS CCM_ID,
    DADOS_2.METEORO,
    DADOS_2.VISIB
FROM     
    (SELECT DISTINCT
        METEORO,
        VISIB
    FROM DADOS) DADOS_2;

-- Insert dos TIPOS_ACIDENTES
INSERT INTO 
    TIPOS_ACIDENTES(TAC_ID, TAC_CLASS_ACID, TAC_TIPO_ACID)
SELECT 
    SEQ_TIPOS_ACIDENTES_ID.NEXTVAL AS TAC_ID,
    DADOS_2.CLASS_ACID,
    DADOS_2.TIPO_ACID
FROM     
    (SELECT DISTINCT
        CLASS_ACID,
        TIPO_ACID
    FROM DADOS) DADOS_2;


-- Insert dos TIPOS_VEICULOS
INSERT INTO 
    TIPOS_VEICULOS(TVC_ID, TVC_VEICULO)
SELECT 
    SEQ_TIPOS_VEICULOS_ID.NEXTVAL AS TVC_ID,
    DADOS_2.TIPO_VEICULO
FROM     
    (SELECT DISTINCT
       REGEXP_SUBSTR(item, '[^=]+', 1, 1) AS TIPO_VEICULO
    FROM (
        SELECT ID,
               REGEXP_SUBSTR(VEÍC, '[^|]+', 1, LEVEL) AS item
        FROM DADOS
        CONNECT BY REGEXP_SUBSTR(VEÍC, '[^|]+', 1, LEVEL) IS NOT NULL
               AND PRIOR ID = ID
               AND PRIOR SYS_GUID() IS NOT NULL
    ) ORDER BY TIPO_VEICULO) DADOS_2
WHERE DADOS_2.TIPO_VEICULO IS NOT NULL;

-- Insert dos ACIDENTES
INSERT INTO ACIDENTES (
    ACD_ID,
    ACD_MARCO_QM,
    ACD_SENTIDO,
    ACD_DTHR_OC,
    ACD_ANO,
    ACD_MES,
    ACD_ILESA_INT,
    ACD_VIT_FATAL_INT,
    ACD_VIT_GRAVE_INT,
    ACD_VIT_LEVE_INT,
    ACD_VIT_MODERADA_INT,
    ACD_VIT_SEMINFO_INT,
    ACD_TIPO_PISTA,
    ACD_LAT_FINAL,
    ACD_LON_FINAL,
    ACD_ROD_ID,
    ACD_TAC_ID,
    ACD_CCM_ID,
    ACD_MUN_ID
)
SELECT
    D.ID, -- sequence para PK
    D.MARCO_QM,
    D.SENTIDO,
    D.DTHR_OC,
    D.ANO,
    D.MÊS,
    D.ILESA_INT,
    D.VIT_FATAL_INT,
    D.VIT_GRAVE_INT,
    D.VIT_LEVE_INT,
    D.VIT_MODERADA_INT,
    D.VIT_SEMINFO_INT,
    D.TIPO_PISTA,
    D.LAT_FINAL,
    D.LON_FINAL,
    R.ROD_ID,
    T.TAC_ID,
    C.CCM_ID,
    M.MUN_ID
FROM DADOS D
JOIN (SELECT * FROM RODOVIAS R2 LEFT JOIN CONCESSIONARIAS C ON R2.ROD_CON_ID = C.CON_ID) R 
  ON (R.ROD_CODIGO_RODOVIA = D.RODOVIA 
     AND R.ROD_DENOMINACAO = D.DENOMINACAO
     AND R.ROD_JURISDICAO = D.JURISDICAO
     AND D.NOME_CONC = R.CON_CONCESSIONARIA)
 OR (D.NOME_CONC = R.CON_CONCESSIONARIA AND R.ROD_CODIGO_RODOVIA = D.RODOVIA 
     AND R.ROD_DENOMINACAO IS NULL AND R.ROD_JURISDICAO IS NULL
     AND D.DENOMINACAO IS NULL AND D.JURISDICAO IS NULL)
JOIN TIPOS_ACIDENTES T
    ON T.TAC_CLASS_ACID = D.CLASS_ACID 
   AND T.TAC_TIPO_ACID = D.TIPO_ACID
JOIN CONDICOES_CLIMATICAS C
    ON C.CCM_METEORO = D.METEORO 
   AND C.CCM_VISIB = D.VISIB
LEFT JOIN MUNICIPIOS M
    ON M.MUN_MUNICIPIO = D."MUNICÍPIO"
   AND M.MUN_REG_DER = D.REGIONAL_DER
   AND M.MUN_REG_ADM = D.REG_ADM_SP
   OR M.MUN_MUNICIPIO IS NULL AND M.MUN_REG_DER IS NULL AND M.MUN_REG_ADM IS NULL;

-- INSERÇÃO DOS DADOS DE VEICULOS_ENVOLVIDOS
INSERT INTO VEICULOS_ENVOLVIDOS (VEN_ID, VEN_QTD, VEN_ACD_ID, VEN_TVC_ID)
SELECT
    SEQ_VEICULOS_ENVOLVIDOS_ID.NEXTVAL,
    TO_NUMBER(REGEXP_SUBSTR(X.VEICULO_PAIR, '[^=]+', 1, 2)) AS QTD, -- pega quantidade após o "="
    X.ACD_ID,
    TV.TVC_ID
FROM (
    SELECT
        ACD.ACD_ID,
        REGEXP_SUBSTR(D.VEÍC, '[^|]+', 1, LEVEL) AS VEICULO_PAIR
    FROM DADOS D
    JOIN ACIDENTES ACD
        ON D.ID = ACD.ACD_ID  -- supondo que você manteve o mesmo ID
        
    WHERE D.VEÍC <> 'SEM INFO/NULO/0'
    CONNECT BY REGEXP_SUBSTR(D.VEÍC, '[^|]+', 1, LEVEL) IS NOT NULL
          AND PRIOR ID = ID
          AND PRIOR SYS_GUID() IS NOT NULL
    
    ) X
JOIN TIPOS_VEICULOS TV
    ON TV.TVC_VEICULO = REGEXP_SUBSTR(X.VEICULO_PAIR, '[^=]+', 1, 1);