DELETE FROM VEICULOS_ENVOLVIDOS;
DELETE FROM ACIDENTES;

DELETE FROM DADOS;

-- COMADOS PARA ZERAR O BANCO DE DADOS
DELETE FROM TIPOS_VEICULOS;
DELETE FROM TIPOS_ACIDENTES;
DELETE FROM RODOVIAS;
DELETE FROM CONCESSIONARIAS;
DELETE FROM CONDICOES_CLIMATICAS;
DELETE FROM MUNICIPIOS;

DROP TABLE VEICULOS_ENVOLVIDOS;
DROP TABLE ACIDENTES;
DROP TABLE TIPOS_VEICULOS;
DROP TABLE TIPOS_ACIDENTES;
DROP TABLE RODOVIAS;
DROP TABLE CONCESSIONARIAS;
DROP TABLE CONDICOES_CLIMATICAS;
DROP TABLE MUNICIPIOS;

DROP TABLE H_VEICULOS_ENVOLVIDOS;
DROP TABLE H_ACIDENTES;
DROP TABLE H_TIPOS_VEICULOS;
DROP TABLE H_TIPOS_ACIDENTES;
DROP TABLE H_RODOVIAS;
DROP TABLE H_CONCESSIONARIAS;
DROP TABLE H_CONDICOES_CLIMATICAS;
DROP TABLE H_MUNICIPIOS;

DROP TABLE DADOS;

DROP SEQUENCE SEQ_MUNICIPIOS_ID;
DROP SEQUENCE SEQ_CONCESSIONARIAS_ID;
DROP SEQUENCE SEQ_RODOVIAS_ID;
DROP SEQUENCE SEQ_CONDICOES_CLIMATICAS_ID;
DROP SEQUENCE SEQ_TIPOS_ACIDENTES_ID;
DROP SEQUENCE SEQ_TIPOS_VEICULOS_ID;
DROP SEQUENCE SEQ_ACIDENTES_ID;
DROP SEQUENCE SEQ_VEICULOS_ENVOLVIDOS_ID;



