



-- Numero de vitimas fatais por ano
SELECT 
    ACD_ANO AS ANO,
    SUM(ACD_VIT_FATAL_INT) AS VITIMAS_FATAIS
FROM ACIDENTES
GROUP BY ACD_ANO
ORDER BY ANO;

-- Quais os tipos de acidentes mais frequentes
SELECT 
    T.TAC_TIPO_ACID AS TIPO_ACIDENTE,
    COUNT(*) AS TOTAL
FROM ACIDENTES A
JOIN TIPOS_ACIDENTES T ON A.ACD_TAC_ID = T.TAC_ID
GROUP BY T.TAC_TIPO_ACID
ORDER BY TOTAL DESC;

-- Quais veículos mais associados em acidentes
SELECT 
    TV.TVC_VEICULO AS TIPO_VEICULO,
    SUM(VE.VEN_QTD) AS TOTAL_ENVOLVIDOS
FROM VEICULOS_ENVOLVIDOS VE
JOIN TIPOS_VEICULOS TV ON VE.VEN_TVC_ID = TV.TVC_ID
GROUP BY TV.TVC_VEICULO
ORDER BY TOTAL_ENVOLVIDOS DESC;

-- Condições climaticas com mais acidentes
SELECT 
    C.CCM_METEORO AS METEORO,
    C.CCM_VISIB AS VISIBILIDADE,
    COUNT(*) AS TOTAL_ACIDENTES
FROM ACIDENTES A
JOIN CONDICOES_CLIMATICAS C ON A.ACD_CCM_ID = C.CCM_ID
GROUP BY C.CCM_METEORO, C.CCM_VISIB
ORDER BY TOTAL_ACIDENTES DESC;
