-- SEQUENCES
CREATE SEQUENCE SEQ_DADOS_ID NOCACHE;
CREATE SEQUENCE SEQ_MUNICIPIOS_ID NOCACHE;
CREATE SEQUENCE SEQ_CONCESSIONARIAS_ID NOCACHE;
CREATE SEQUENCE SEQ_RODOVIAS_ID NOCACHE;
CREATE SEQUENCE SEQ_CONDICOES_CLIMATICAS_ID NOCACHE;
CREATE SEQUENCE SEQ_TIPOS_ACIDENTES_ID NOCACHE;
CREATE SEQUENCE SEQ_TIPOS_VEICULOS_ID NOCACHE;
CREATE SEQUENCE SEQ_ACIDENTES_ID NOCACHE;
CREATE SEQUENCE SEQ_VEICULOS_ENVOLVIDOS_ID NOCACHE;



-- SEQUENCES
-- ALTER SEQUENCE SEQ_DADOS_ID RESTART;
-- ALTER SEQUENCE SEQ_MUNICIPIOS_ID RESTART;
-- ALTER SEQUENCE SEQ_CONCESSIONARIAS_ID RESTART;
-- ALTER SEQUENCE SEQ_RODOVIAS_ID RESTART;
-- ALTER SEQUENCE SEQ_CONDICOES_CLIMATICAS_ID RESTART;
-- ALTER SEQUENCE SEQ_TIPOS_ACIDENTES_ID RESTART;
-- ALTER SEQUENCE SEQ_TIPOS_VEICULOS_ID RESTART;
-- ALTER SEQUENCE SEQ_ACIDENTES_ID RESTART;
-- ALTER SEQUENCE SEQ_VEICULOS_ENVOLVIDOS_ID RESTART;