ALTER SESSION SET "_ORACLE_SCRIPT" = true;
    
CREATE USER DWUSER IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT connect, resource TO DW_USER;

GRANT CREATE SESSION TO DWUSER;
GRANT CREATE TABLE TO DWUSER;
GRANT CREATE VIEW TO DWUSER;
GRANT CREATE MATERIALIZED VIEW TO DWUSER;


GRANT SELECT ON APP.MUNICIPIOS TO DWUSER;
GRANT SELECT ON APP.ACIDENTES TO DWUSER;
GRANT SELECT ON APP.CONDICOES_CLIMATICAS TO DWUSER;
GRANT SELECT ON APP.CONCESSIONARIAS TO DWUSER;
GRANT SELECT ON APP.RODOVIAS TO DWUSER;
GRANT SELECT ON APP.TIPOS_ACIDENTES TO DWUSER;
GRANT SELECT ON APP.TIPOS_VEICULOS TO DWUSER;
GRANT SELECT ON APP.VEICULOS_ENVOLVIDOS TO DWUSER;

GRANT SELECT ON APP.H_MUNICIPIOS TO DWUSER;
GRANT SELECT ON APP.H_ACIDENTES TO DWUSER;
GRANT SELECT ON APP.H_CONDICOES_CLIMATICAS TO DWUSER;
GRANT SELECT ON APP.H_CONCESSIONARIAS TO DWUSER;
GRANT SELECT ON APP.H_RODOVIAS TO DWUSER;
GRANT SELECT ON APP.H_TIPOS_ACIDENTES TO DWUSER;
GRANT SELECT ON APP.H_TIPOS_VEICULOS TO DWUSER;
GRANT SELECT ON APP.H_VEICULOS_ENVOLVIDOS TO DWUSER;
