ALTER SESSION SET "_ORACLE_SCRIPT" = true;


CREATE TABLESPACE DW_DATA
    DATAFILE 'dw_data01.dbf' SIZE 2G
    AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

CREATE TEMPORARY TABLESPACE DW_TEMP
    TEMPFILE 'dw_temp01.dbf' SIZE 1G
    AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
    
    
CREATE USER DW_USER IDENTIFIED BY APP123
DEFAULT TABLESPACE DW_DATA
TEMPORARY TABLESPACE DW_TEMP
QUOTA UNLIMITED ON DW_DATA;

GRANT connect, resource TO DW_USER;

GRANT CREATE SESSION TO DW_USER;
GRANT CREATE TABLE TO DW_USER;
GRANT CREATE VIEW TO DW_USER;
GRANT CREATE PROCEDURE TO DW_USER;
GRANT CREATE SEQUENCE TO DW_USER;