-- VIEW: TODOS VEICULOS ENVOLVIDOS EM ACIDENTES
CREATE OR REPLACE VIEW VIEW_TODOS_VEICULOS_ENVOLVIDOS AS
SELECT
    VE.VEN_ID,
    VE.VEN_QTD,
    VE.VEN_ACD_ID,
    VE.VEN_TVC_ID,
    CASE
        WHEN TV.TVC_VEICULO IN ('SEM INFO/NULO/0', 'NÃO INFORMADO', 'NÃO IDENTIFICADO', 'NÃO SE APLICA')
        THEN 'SEM INFORMAÇÃO'
        ELSE TV.TVC_VEICULO
    END AS VEICULO
FROM (SELECT
        VEN_ID,
        VEN_QTD,
        VEN_ACD_ID,
        VEN_TVC_ID
    FROM APP.VEICULOS_ENVOLVIDOS
    UNION ALL
    SELECT
        H_VEN_ID,
        H_VEN_QTD,
        H_VEN_ACD_ID,
        H_VEN_TVC_ID
    FROM APP.H_VEICULOS_ENVOLVIDOS) VE
JOIN APP.TIPOS_VEICULOS TV ON VE.VEN_TVC_ID = TV.TVC_ID;

CREATE OR REPLACE VIEW VIEW_TODOS_ACIDENTES AS
SELECT
    A.ACD_ID,
    A.ACD_DTHR_OC,
    A.ACD_ANO,
    A.ACD_MES,
    A.ACD_ILESA_INT,
    A.ACD_VIT_FATAL_INT,
    A.ACD_VIT_GRAVE_INT,
    A.ACD_VIT_LEVE_INT,
    A.ACD_VIT_MODERADA_INT,
    A.ACD_VIT_SEMINFO_INT,
    A.ACD_TIPO_PISTA,
    A.ACD_ROD_ID,
    A.ACD_TAC_ID,
    A.ACD_CCM_ID,
    A.ACD_MUN_ID
FROM APP.ACIDENTES A
UNION ALL
SELECT 
    HA.H_ACD_ID,
    HA.H_ACD_DTHR_OC,
    HA.H_ACD_ANO,
    HA.H_ACD_MES,
    HA.H_ACD_ILESA_INT,
    HA.H_ACD_VIT_FATAL_INT,
    HA.H_ACD_VIT_GRAVE_INT,
    HA.H_ACD_VIT_LEVE_INT,
    HA.H_ACD_VIT_MODERADA_INT,
    HA.H_ACD_VIT_SEMINFO_INT,
    HA.H_ACD_TIPO_PISTA,
    HA.H_ACD_ROD_ID,
    HA.H_ACD_TAC_ID,
    HA.H_ACD_CCM_ID,
    HA.H_ACD_MUN_ID
FROM APP.H_ACIDENTES HA;






