CREATE MATERIALIZED VIEW MVIEW_PORC_ACIDENTES_MUNICIPIOS
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT 
    M.MUN_MUNICIPIO AS MUNICIPIO,
    SUM(A.ACD_VIT_SEMINFO_INT) AS "VIT. SEM INFO",
    SUM(A.ACD_VIT_MODERADA_INT) AS "VIT. MODERADA",
    SUM(A.ACD_VIT_LEVE_INT) AS "VIT. LEVE",
    SUM(A.ACD_VIT_GRAVE_INT) AS "VIT. GRAVE",
    SUM(A.ACD_VIT_FATAL_INT) AS "VIT. FATAL",
    COUNT(*) AS TOTAL_ACIDENTES,
    TO_CHAR(
        (COUNT(*) / (SELECT COUNT(*) FROM APP.ACIDENTES)) * 100, 'FM999.0'
    ) || '%' AS PORCENTAGEM
FROM APP.ACIDENTES A
JOIN APP.MUNICIPIOS M ON A.ACD_MUN_ID = M.MUN_ID
GROUP BY M.MUN_MUNICIPIO
ORDER BY TOTAL_ACIDENTES DESC;