DROP MATERIALIZED VIEW MVIEW_PORC_ACIDENTES_MUNICIPIOS;
DROP MATERIALIZED VIEW MVIEW_RANK_CRESC_ACIDENTES_MUNICIPIOS;
DROP MATERIALIZED VIEW MVIEW_RANK_PERC_ACIDENTES_RODOVIAS;
DROP MATERIALIZED VIEW MVIEW_ACIDENTES_TIPO_ANO;
DROP MATERIALIZED VIEW MVIEW_CLIMAS_COM_MAIS_ACIDENTES_POR_ANO;
DROP MATERIALIZED VIEW MVIEW_TIPOS_VEICULOS_ACIDENTES_POR_ANO;
DROP MATERIALIZED VIEW MVIEW_MAIOR_CRESCIMENTO_ACIDENTES_POR_ANO;
DROP MATERIALIZED VIEW MVIEW_ACIDENTES_RODOVIA_POR_ANO;

-- View 1 - Porcentagem de acidentes por município
CREATE MATERIALIZED VIEW MVIEW_PORC_ACIDENTES_MUNICIPIOS
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT 
    M.MUN_MUNICIPIO AS MUNICIPIO,
    SUM(A.ACD_VIT_SEMINFO_INT) AS "VIT. SEM INFO",
    SUM(A.ACD_VIT_MODERADA_INT) AS "VIT. MODERADA",
    SUM(A.ACD_VIT_LEVE_INT) AS "VIT. LEVE",
    SUM(A.ACD_VIT_GRAVE_INT) AS "VIT. GRAVE",
    SUM(A.ACD_VIT_FATAL_INT) AS "VIT. FATAL",
    COUNT(*) AS TOTAL_ACIDENTES,
    TO_CHAR(
        (COUNT(*) / (SELECT COUNT(*) FROM APP.ACIDENTES)) * 100, 'FM999.0'
    ) || '%' AS PORCENTAGEM
FROM APP.ACIDENTES A
JOIN APP.MUNICIPIOS M ON A.ACD_MUN_ID = M.MUN_ID
GROUP BY M.MUN_MUNICIPIO;

-- View 2 - Ranking de crescimento de acidentes por município
CREATE MATERIALIZED VIEW MVIEW_RANK_CRESC_ACIDENTES_MUNICIPIOS
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT 
    NOME_MUNICIPIO, 
    ANO, 
    CRESCIMENTO, 
    DENSE_RANK() OVER (PARTITION BY ANO ORDER BY CRESCIMENTO DESC) AS RANKING
FROM (
    SELECT NOME_MUNICIPIO,
           ANO,
           NVL(SUM(CASE WHEN PERIODO = 'Atual' THEN TOTAL END),0) -
           NVL(SUM(CASE WHEN PERIODO = 'Histórico' THEN TOTAL END),0) AS CRESCIMENTO
    FROM (
        SELECT M.MUN_MUNICIPIO AS NOME_MUNICIPIO,
               A.ACD_ANO AS ANO,
               'Atual' AS PERIODO,
               COUNT(A.ACD_ID) AS TOTAL
        FROM APP.ACIDENTES A
        JOIN APP.MUNICIPIOS M ON A.ACD_MUN_ID = M.MUN_ID
        GROUP BY M.MUN_MUNICIPIO, A.ACD_ANO

        UNION ALL

        SELECT M.MUN_MUNICIPIO AS NOME_MUNICIPIO,
               HA.H_ACD_ANO AS ANO,
               'Histórico' AS PERIODO,
               COUNT(HA.H_ACD_ID) AS TOTAL
        FROM APP.H_ACIDENTES HA
        JOIN APP.MUNICIPIOS M ON HA.H_ACD_MUN_ID = M.MUN_ID
        GROUP BY M.MUN_MUNICIPIO, HA.H_ACD_ANO
    )
    GROUP BY NOME_MUNICIPIO, ANO
)
ORDER BY ANO, RANKING;


-- View 3 - Ranking das rodovias com maior percentual de acidentes
CREATE MATERIALIZED VIEW MVIEW_RANK_PERC_ACIDENTES_RODOVIAS
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
    RODOVIA,
    TOTAL_ACIDENTES,
    PORCENTAGEM,
    DENSE_RANK() OVER (ORDER BY TOTAL_ACIDENTES DESC) AS RANKING
FROM (
    SELECT 
        R.ROD_CODIGO_RODOVIA AS RODOVIA,
        COUNT(*) AS TOTAL_ACIDENTES,
        TO_CHAR(
            (COUNT(*) / (SELECT COUNT(*) FROM APP.ACIDENTES)) * 100,
            'FM999.0'
        ) || '%' AS PORCENTAGEM
    FROM APP.ACIDENTES A
    JOIN APP.RODOVIAS R ON A.ACD_ROD_ID = R.ROD_ID
    GROUP BY R.ROD_CODIGO_RODOVIA
);

-- View 4 - Acidentes por tipo e ano (atual x histórico)
CREATE MATERIALIZED VIEW MVIEW_ACIDENTES_TIPO_ANO
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT TA.TAC_TIPO_ACID AS TIPO_ACIDENTE,
       A.ACD_ANO AS ANO,
       COUNT(A.ACD_ID) AS TOTAL
FROM APP.ACIDENTES A
JOIN APP.TIPOS_ACIDENTES TA ON A.ACD_TAC_ID = TA.TAC_ID
GROUP BY TA.TAC_TIPO_ACID, A.ACD_ANO

UNION ALL

SELECT TA.TAC_TIPO_ACID AS TIPO_ACIDENTE,
       HA.H_ACD_ANO AS ANO,
       COUNT(HA.H_ACD_ID) AS TOTAL
FROM APP.H_ACIDENTES HA
JOIN APP.TIPOS_ACIDENTES TA ON HA.H_ACD_TAC_ID = TA.TAC_ID
GROUP BY TA.TAC_TIPO_ACID, HA.H_ACD_ANO;

-- View 5 - Condições climáticas mais associadas a acidentes por ano (atual x histórico)
CREATE MATERIALIZED VIEW MVIEW_CLIMAS_COM_MAIS_ACIDENTES_POR_ANO
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT CC.CCM_METEORO || ' / ' || CC.CCM_VISIB AS CONDICAO_CLIMATICA,
       A.ACD_ANO AS ANO,
       'Atual' AS PERIODO,
       COUNT(A.ACD_ID) AS TOTAL
FROM APP.ACIDENTES A
JOIN APP.CONDICOES_CLIMATICAS CC ON A.ACD_CCM_ID = CC.CCM_ID
GROUP BY CC.CCM_METEORO, CC.CCM_VISIB, A.ACD_ANO

UNION ALL

SELECT CC.CCM_METEORO || ' / ' || CC.CCM_VISIB AS CONDICAO_CLIMATICA,
       HA.H_ACD_ANO AS ANO,
       'Histórico' AS PERIODO,
       COUNT(HA.H_ACD_ID) AS TOTAL
FROM APP.H_ACIDENTES HA
JOIN APP.CONDICOES_CLIMATICAS CC ON HA.H_ACD_CCM_ID = CC.CCM_ID
GROUP BY CC.CCM_METEORO, CC.CCM_VISIB, HA.H_ACD_ANO;


-- View 6 - Veículos envolvidos em acidentes por ano (atual x histórico)
CREATE MATERIALIZED VIEW MVIEW_TIPOS_VEICULOS_ACIDENTES_POR_ANO
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT TV.TVC_VEICULO,
       A.ACD_ANO AS ANO,
       'Atual' AS PERIODO,
       COUNT(VE.VEN_ID) AS TOTAL
FROM APP.VEICULOS_ENVOLVIDOS VE
JOIN APP.TIPOS_VEICULOS TV ON VE.VEN_TVC_ID = TV.TVC_ID
JOIN APP.ACIDENTES A ON VE.VEN_ACD_ID = A.ACD_ID
GROUP BY TV.TVC_VEICULO, A.ACD_ANO

UNION ALL

SELECT TV.TVC_VEICULO,
       HA.H_ACD_ANO AS ANO,
       'Histórico' AS PERIODO,
       COUNT(HVE.H_VEN_ID) AS TOTAL
FROM APP.H_VEICULOS_ENVOLVIDOS HVE
JOIN APP.TIPOS_VEICULOS TV ON HVE.H_VEN_TVC_ID = TV.TVC_ID
JOIN APP.H_ACIDENTES HA ON HVE.H_VEN_ACD_ID = HA.H_ACD_ID
GROUP BY TV.TVC_VEICULO, HA.H_ACD_ANO;

-- View 7 - Ranking dos municípios com maior crescimento de acidentes por ano
CREATE MATERIALIZED VIEW MVIEW_MAIOR_CRESCIMENTO_ACIDENTES_POR_ANO
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT NOME_MUNICIPIO,
       ANO,
       CRESCIMENTO,
       DENSE_RANK() OVER (PARTITION BY ANO ORDER BY CRESCIMENTO DESC) AS RANKING
FROM (
    SELECT NOME_MUNICIPIO,
           ANO,
           NVL(SUM(CASE WHEN PERIODO = 'Atual' THEN TOTAL END),0) -
           NVL(SUM(CASE WHEN PERIODO = 'Histórico' THEN TOTAL END),0) AS CRESCIMENTO
    FROM (
        SELECT M.MUN_MUNICIPIO AS NOME_MUNICIPIO,
               A.ACD_ANO AS ANO,
               'Atual' AS PERIODO,
               COUNT(A.ACD_ID) AS TOTAL
        FROM APP.ACIDENTES A
        JOIN APP.MUNICIPIOS M ON A.ACD_MUN_ID = M.MUN_ID
        GROUP BY M.MUN_MUNICIPIO, A.ACD_ANO

        UNION ALL

        SELECT M.MUN_MUNICIPIO AS NOME_MUNICIPIO,
               HA.H_ACD_ANO AS ANO,
               'Histórico' AS PERIODO,
               COUNT(HA.H_ACD_ID) AS TOTAL
        FROM APP.H_ACIDENTES HA
        JOIN APP.MUNICIPIOS M ON HA.H_ACD_MUN_ID = M.MUN_ID
        GROUP BY M.MUN_MUNICIPIO, HA.H_ACD_ANO
    )
    GROUP BY NOME_MUNICIPIO, ANO
)
ORDER BY ANO, RANKING;


-- View 8 - Acidentes por município e rodovia por ano (atual x histórico)
CREATE MATERIALIZED VIEW MVIEW_ACIDENTES_RODOVIA_POR_ANO
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT M.MUN_MUNICIPIO,
       R.ROD_CODIGO_RODOVIA,
       A.ACD_ANO AS ANO,
       'Atual' AS PERIODO,
       COUNT(A.ACD_ID) AS TOTAL
FROM APP.ACIDENTES A
JOIN APP.MUNICIPIOS M ON A.ACD_MUN_ID = M.MUN_ID
JOIN APP.RODOVIAS R ON A.ACD_ROD_ID = R.ROD_ID
GROUP BY M.MUN_MUNICIPIO, R.ROD_CODIGO_RODOVIA, A.ACD_ANO

UNION ALL

SELECT M.MUN_MUNICIPIO,
       R.ROD_CODIGO_RODOVIA,
       HA.H_ACD_ANO AS ANO,
       'Histórico' AS PERIODO,
       COUNT(HA.H_ACD_ID) AS TOTAL
FROM APP.H_ACIDENTES HA
JOIN APP.MUNICIPIOS M ON HA.H_ACD_MUN_ID = M.MUN_ID
JOIN APP.RODOVIAS R ON HA.H_ACD_ROD_ID = R.ROD_ID
GROUP BY M.MUN_MUNICIPIO, R.ROD_CODIGO_RODOVIA, HA.H_ACD_ANO

ORDER BY MUN_MUNICIPIO, ROD_CODIGO_RODOVIA, ANO, PERIODO;



















