-- MVIEW 01: ACIDENTES POR RODOVIA E MUNICIPIO
CREATE MATERIALIZED VIEW MVIEW_ACIDENTES_POR_RODOVIA_MUNICIPIO
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
    *
FROM (SELECT 
        R.ROD_CODIGO_RODOVIA AS CODIGO_RODOVIA,
        R.ROD_DENOMINACAO AS DENOMINACAO_RODOVIA,
        M.MUN_MUNICIPIO AS MUNICIPIO,
        A.ACD_MES AS MES,
        A.ACD_ANO AS ANO,
        SUM(A.ACD_ILESA_INT) AS VITIMAS_ILESAS,
        SUM(A.ACD_VIT_FATAL_INT) AS VITIMAS_FATAIS,
        SUM(A.ACD_VIT_GRAVE_INT) AS VITIMAS_GRAVES,
        SUM(A.ACD_VIT_LEVE_INT) AS VITIMAS_LEVES,
        SUM(A.ACD_VIT_MODERADA_INT) AS VITIMAS_MODERADAS,
        SUM(A.ACD_VIT_SEMINFO_INT) AS VITIMAS_SEM_INFO,
        COUNT(A.ACD_ID) AS TOTAL_ACIDENTES
    FROM APP.ACIDENTES A
    JOIN APP.MUNICIPIOS M   ON A.ACD_MUN_ID = M.MUN_ID
    JOIN APP.RODOVIAS R     ON R.ROD_ID = A.ACD_ROD_ID
    GROUP BY R.ROD_CODIGO_RODOVIA, R.ROD_DENOMINACAO, M.MUN_MUNICIPIO, A.ACD_MES, A.ACD_ANO
    
    UNION ALL
    
    SELECT 
        H_R.ROD_CODIGO_RODOVIA AS CODIGO_RODOVIA,
        H_R.ROD_DENOMINACAO AS DENOMINACAO_RODOVIA,
        H_M.MUN_MUNICIPIO AS MUNICIPIO,
        H_A.H_ACD_MES AS MES, 
        H_A.H_ACD_ANO AS ANO,
        SUM(H_A.H_ACD_ILESA_INT) AS VITIMAS_ILESAS,
        SUM(H_A.H_ACD_VIT_FATAL_INT) AS VITIMAS_FATAIS,
        SUM(H_A.H_ACD_VIT_GRAVE_INT) AS VITIMAS_GRAVES,
        SUM(H_A.H_ACD_VIT_LEVE_INT) AS VITIMAS_LEVES,
        SUM(H_A.H_ACD_VIT_MODERADA_INT) AS VITIMAS_MODERADAS,
        SUM(H_A.H_ACD_VIT_SEMINFO_INT) AS VITIMAS_SEM_INFO,
        COUNT(H_A.H_ACD_ID) AS TOTAL_ACIDENTES
    FROM APP.H_ACIDENTES H_A
    JOIN APP.MUNICIPIOS H_M ON H_A.H_ACD_MUN_ID = H_M.MUN_ID
    JOIN APP.RODOVIAS H_R ON H_A.H_ACD_ROD_ID = H_R.ROD_ID
    GROUP BY H_R.ROD_CODIGO_RODOVIA, H_R.ROD_DENOMINACAO, H_M.MUN_MUNICIPIO, H_A.H_ACD_MES, H_A.H_ACD_ANO)

ORDER BY DENOMINACAO_RODOVIA;

-- MVIEW 02: ACIDENTES POR CONDICOES CLIMATICAS E VISIBILIDADE
CREATE MATERIALIZED VIEW MVIEW_ACIDENTES_POR_CONDICOES
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT 
    METEOROLOGIA,
    VISIBILIDADE,
    ACD_ANO,
    ACD_MES,
    SUM(ACD_ILESA_INT) AS VITIMAS_ILESAS,
    SUM(ACD_VIT_FATAL_INT) AS VITIMAS_FATAIS,
    SUM(ACD_VIT_GRAVE_INT) AS VITIMAS_GRAVES,
    SUM(ACD_VIT_LEVE_INT) AS VITIMAS_LEVES,
    SUM(ACD_VIT_MODERADA_INT) AS VITIMAS_MODERADAS,
    SUM(ACD_VIT_SEMINFO_INT) AS VITIMAS_SEM_INFO,
    COUNT(ACD_ID) AS TOTAL_ACIDENTES
FROM (SELECT
        CASE
            WHEN C.CCM_METEORO IN ('SEM INFO/NULO/0', 'NÃO INFORMADA')
            THEN 'SEM INFORMAÇÃO'
            ELSE C.CCM_METEORO
        END AS METEOROLOGIA,
    
        -- Padroniza a coluna CCM_VISIB
        CASE
            WHEN C.CCM_VISIB IN ('NÃO DEFINIDO', 'SEM INFO/NULO/0', 'NÃO INFORMADA')
            THEN 'SEM INFORMAÇÃO'
            ELSE C.CCM_VISIB
        END AS VISIBILIDADE,
        A.ACD_ID,
        A.ACD_ANO,
        A.ACD_MES,
        A.ACD_ILESA_INT,
        A.ACD_VIT_FATAL_INT,
        A.ACD_VIT_GRAVE_INT,
        A.ACD_VIT_LEVE_INT,
        A.ACD_VIT_MODERADA_INT,
        A.ACD_VIT_SEMINFO_INT,
        A.ACD_CCM_ID
    FROM (SELECT
            ACD_ID,
            ACD_ANO,
            ACD_MES,
            ACD_ILESA_INT,
            ACD_VIT_FATAL_INT,
            ACD_VIT_GRAVE_INT,
            ACD_VIT_LEVE_INT,
            ACD_VIT_MODERADA_INT,
            ACD_VIT_SEMINFO_INT,
            ACD_CCM_ID
        FROM APP.ACIDENTES
        
        UNION ALL
        
        SELECT
            H_ACD_ID,
            H_ACD_ANO,
            H_ACD_MES,
            H_ACD_ILESA_INT,
            H_ACD_VIT_FATAL_INT,
            H_ACD_VIT_GRAVE_INT,
            H_ACD_VIT_LEVE_INT,
            H_ACD_VIT_MODERADA_INT,
            H_ACD_VIT_SEMINFO_INT,
            H_ACD_CCM_ID
        FROM APP.H_ACIDENTES) A
    JOIN APP.CONDICOES_CLIMATICAS C ON A.ACD_CCM_ID = C.CCM_ID)
GROUP BY METEOROLOGIA, VISIBILIDADE, ACD_ANO, ACD_MES;

-- MVIEW 03: VEICULOS ENVOLVIDOS E DETALHES DOS ACIDENTES
CREATE MATERIALIZED VIEW MVIEW_VEICULOS_ENVOLVIDOS_ACIDENTES
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
    VEICULO,
    AC.ACD_ANO,
    AC.ACD_MES,
    SUM(VE.VEN_QTD) AS QTDE_ENVOLVIMENTOS,
    SUM(AC.ACD_ILESA_INT) AS VITIMAS_ILESAS,
    SUM(AC.ACD_VIT_FATAL_INT) AS VITIMAS_FATAIS,
    SUM(AC.ACD_VIT_GRAVE_INT) AS VITIMAS_GRAVES,
    SUM(AC.ACD_VIT_LEVE_INT) AS VITIMAS_LEVE,
    SUM(AC.ACD_VIT_MODERADA_INT) AS VITIMAS_MODERADAS,
    SUM(AC.ACD_VIT_SEMINFO_INT) AS VITIMAS_SEM_INFO,
    COUNT(AC.ACD_ID) AS TODOS_ACIDENTES

FROM VIEW_TODOS_VEICULOS_ENVOLVIDOS VE
LEFT JOIN APP.TIPOS_VEICULOS TV ON VE.VEN_TVC_ID = TV.TVC_ID
LEFT JOIN VIEW_TODOS_ACIDENTES AC ON AC.ACD_ID = VE.VEN_ACD_ID
GROUP BY VEICULO, AC.ACD_ANO, AC.ACD_MES
ORDER BY AC.ACD_ANO, AC.ACD_MES;

-- MVIEW 04: TIPOS E CLISSIFICACOES DE ACIDENTES
CREATE MATERIALIZED VIEW MVIEW_TIPOS_CLASSIFICACOES_ACIDENTES
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
    TAC_CLASS_ACID,
    TAC_TIPO_ACID,
    MES,
    ANO, 
    SUM(ACD_ILESA_INT) AS VITIMAS_ILESAS,
    SUM(ACD_VIT_FATAL_INT) AS VITIMAS_FATAIS,
    SUM(ACD_VIT_GRAVE_INT) AS VITIMAS_GRAVES,
    SUM(ACD_VIT_LEVE_INT) AS VITIMAS_LEVES,
    SUM(ACD_VIT_MODERADA_INT) AS VITIMAS_MODERADAS,
    SUM(ACD_VIT_SEMINFO_INT) AS VITIMAS_SEM_INFO,
    COUNT(ACD_ID) AS TOTAL_ACIDENTES
FROM (SELECT
        T.TAC_CLASS_ACID,
        T.TAC_TIPO_ACID,
        A.ACD_ID,
        A.ACD_MES AS MES,
        A.ACD_ANO AS ANO,
        A.ACD_ILESA_INT,
        A.ACD_VIT_FATAL_INT,
        A.ACD_VIT_GRAVE_INT,
        A.ACD_VIT_LEVE_INT,
        A.ACD_VIT_MODERADA_INT,
        A.ACD_VIT_SEMINFO_INT
    FROM APP.ACIDENTES A
    JOIN APP.TIPOS_ACIDENTES T ON A.ACD_TAC_ID = T.TAC_ID
    UNION ALL
    SELECT
        HTAC.TAC_CLASS_ACID,
        HTAC.TAC_TIPO_ACID,
        HA.H_ACD_ID,
        HA.H_ACD_MES AS MES,
        HA.H_ACD_ANO AS ANO,
        HA.H_ACD_ILESA_INT,
        HA.H_ACD_VIT_FATAL_INT,
        HA.H_ACD_VIT_GRAVE_INT,
        HA.H_ACD_VIT_LEVE_INT,
        HA.H_ACD_VIT_MODERADA_INT,
        HA.H_ACD_VIT_SEMINFO_INT
    FROM APP.H_ACIDENTES HA
    JOIN APP.TIPOS_ACIDENTES HTAC ON HA.H_ACD_TAC_ID = HTAC.TAC_ID)
GROUP BY TAC_CLASS_ACID, TAC_TIPO_ACID, ANO, MES;

