SELECT * FROM MVIEW_ACIDENTES_POR_RODOVIA_MUNICIPIO;
SELECT * FROM MVIEW_ACIDENTES_POR_CONDICOES;
SELECT * FROM MVIEW_VEICULOS_ENVOLVIDOS_ACIDENTES;
SELECT * FROM MVIEW_TIPOS_CLASSIFICACOES_ACIDENTES;

-- CONSULTA 01: RODOVIAS COM MAIOR NUMERO DE ACIDENTES FATAIS E PERCENTUAL DE ACIDENTES FATAIS
SELECT
    ACIDENTES.CODIGO_RODOVIA,
    ACIDENTES.DENOMINACAO_RODOVIA,
    
    -- 1. Calcula o total de vítimas fatais por rodovia (para identificar as rodovias com maior incidência)
    SUM(ACIDENTES.VITIMAS_FATAIS) AS TOTAL_VITIMAS_FATAIS,
    
    -- Calcula o total de vítimas (incluindo ilesas) e acidentes para o cálculo do percentual
    SUM(ACIDENTES.TOTAL_ACIDENTES) AS TOTAL_ACIDENTES_RODOVIA,
    SUM(ACIDENTES.VITIMAS_ILESAS + 
        ACIDENTES.VITIMAS_FATAIS + 
        ACIDENTES.VITIMAS_GRAVES + 
        ACIDENTES.VITIMAS_LEVES + 
        ACIDENTES.VITIMAS_MODERADAS + 
        ACIDENTES.VITIMAS_SEM_INFO) AS TOTAL_PESSOAS_ENVOLVIDAS,
    
    -- 2. Calcula o percentual de vítimas fatais em relação ao total de pessoas envolvidas.
    -- Utiliza CAST e NULLIF para garantir o cálculo decimal e evitar divisão por zero.
    CAST(
        (SUM(ACIDENTES.VITIMAS_FATAIS) * 100.0) / 
        NULLIF(SUM(ACIDENTES.VITIMAS_ILESAS + 
                   ACIDENTES.VITIMAS_FATAIS + 
                   ACIDENTES.VITIMAS_GRAVES + 
                   ACIDENTES.VITIMAS_LEVES + 
                   ACIDENTES.VITIMAS_MODERADAS + 
                   ACIDENTES.VITIMAS_SEM_INFO), 0)
    AS DECIMAL(10, 2)) AS PERCENTUAL_VITIMAS_FATAIS
    
FROM MVIEW_ACIDENTES_POR_RODOVIA_MUNICIPIO ACIDENTES
GROUP BY ACIDENTES.CODIGO_RODOVIA, ACIDENTES.DENOMINACAO_RODOVIA
ORDER BY TOTAL_VITIMAS_FATAIS DESC, PERCENTUAL_VITIMAS_FATAIS DESC;

-- CONSULTA 02: CRESCIMENTO DE ACIDENTES GRAVES NAS RODOVIAS ANO A ANO
WITH BASE AS (
    SELECT 
        ANO,
        SUM(VITIMAS_ILESAS) AS ILESAS,
        SUM(VITIMAS_FATAIS) AS FATAIS,
        SUM(VITIMAS_GRAVES) AS GRAVES,
        SUM(VITIMAS_LEVES) AS LEVES,
        SUM(VITIMAS_MODERADAS) AS MODERADAS,
        SUM(VITIMAS_SEM_INFO) AS SEM_INFO,
        SUM(TOTAL_ACIDENTES) AS TOTAL
    FROM MVIEW_ACIDENTES_POR_RODOVIA_MUNICIPIO
    GROUP BY ANO
),
COMPARACAO AS (
    SELECT
        B1.ANO AS ANO_ATUAL,
        B2.ANO AS ANO_ANTERIOR,

        -- Valores
        B1.TOTAL AS TOTAL_ATUAL,
        B2.TOTAL AS TOTAL_ANTERIOR,

        -- Diferença
        (B1.TOTAL - B2.TOTAL) AS DIFERENCA_TOTAL,

        -- Percentual
        CASE WHEN B2.TOTAL = 0 THEN NULL
             ELSE ROUND(((B1.TOTAL - B2.TOTAL) / B2.TOTAL) * 100, 2)
        END AS CRESCIMENTO_TOTAL_PCT,

        -- Exemplo com tipo específico
        B1.FATAIS AS FATAIS_ATUAL,
        B2.FATAIS AS FATAIS_ANTERIOR,
        (B1.FATAIS - B2.FATAIS) AS DIF_FATAIS,

        CASE WHEN B2.FATAIS = 0 THEN NULL
             ELSE ROUND(((B1.FATAIS - B2.FATAIS) / B2.FATAIS) * 100, 2)
        END AS CRESCIMENTO_FATAIS_PCT

    FROM BASE B1
    JOIN BASE B2 
         ON B1.ANO = B2.ANO + 5  -- comparação 2014→2019 e 2019→2024
)
SELECT *
FROM COMPARACAO
ORDER BY ANO_ATUAL;

-- CONSULTA 03: RANKING DAS CONDICOES CLIMATICAS COM MAIS ACIDENTES FATAIS
SELECT
    METEOROLOGIA,
    VISIBILIDADE,
    SUM(VITIMAS_FATAIS) AS TOTAL_ACIDENTES_FATAIS,
    SUM(TOTAL_ACIDENTES) AS TOTAL_ACIDENTES,
    RANK() OVER (ORDER BY SUM(VITIMAS_FATAIS) DESC) AS RANKING_FATAIS
FROM MVIEW_ACIDENTES_POR_CONDICOES
GROUP BY METEOROLOGIA, VISIBILIDADE
ORDER BY TOTAL_ACIDENTES_FATAIS DESC;

-- CONSULTA 04: PORCENTUAL DE ACIDENTES POR COMBINAÇÃO DE CONDIÇÕES CLIMÁTICAS E VISIBILIDADE
WITH TOTAL AS (
    SELECT SUM(TOTAL_ACIDENTES) AS TOTAL_GERAL
    FROM MVIEW_ACIDENTES_POR_CONDICOES
)
SELECT
    METEOROLOGIA,
    VISIBILIDADE,
    SUM(TOTAL_ACIDENTES) AS TOTAL_ACIDENTES,
    ROUND( (SUM(TOTAL_ACIDENTES) / T.TOTAL_GERAL) * 100, 2 ) AS PERCENTUAL
FROM MVIEW_ACIDENTES_POR_CONDICOES M
CROSS JOIN TOTAL T
GROUP BY METEOROLOGIA, VISIBILIDADE, T.TOTAL_GERAL
ORDER BY PERCENTUAL DESC;

-- CONSULTA 05: TIPO DE VEICULO MAIS ENVOLVIDO EM ACIDENTES COM VITIMAS FATAIS
SELECT
    VEICULO,
    COUNT(*) AS QTDE_ENVOLVIMENTOS,
    SUM(ACD_VIT_FATAL_INT) AS VITIMAS_FATAIS,
    RANK() OVER (ORDER BY SUM(ACD_VIT_FATAL_INT) DESC) AS RANKING_FATAL
FROM MVIEW_VEICULOS_ENVOLVIDOS_ACIDENTES
WHERE ACD_VIT_FATAL_INT > 0
GROUP BY VEICULO
ORDER BY VITIMAS_FATAIS DESC;

-- CONSULTA 06: PERCENTUAL DE VEICULOS ENVOLVIDOS EM ACIDENTES FATAIS POR TIPO DE VEICULO
WITH BASE AS (
    SELECT
        VEICULO,
        SUM(ACD_VIT_FATAL_INT) AS VITIMAS_FATAIS
    FROM MVIEW_VEICULOS_ENVOLVIDOS_ACIDENTES
    WHERE ACD_VIT_FATAL_INT > 0
    GROUP BY VEICULO
),
TOTAL AS (
    SELECT SUM(VITIMAS_FATAIS) AS TOTAL_FATAIS FROM BASE
)
SELECT
    B.VEICULO,
    B.VITIMAS_FATAIS,
    ROUND((B.VITIMAS_FATAIS / T.TOTAL_FATAIS) * 100, 2) AS PERCENTUAL
FROM BASE B CROSS JOIN TOTAL T
ORDER BY B.VITIMAS_FATAIS DESC;

-- CONSULTA 07: MEDIA DE ACIDENTES POR TIPO E CLASSIFICACAO ANO A ANO
SELECT
    TAC_CLASS_ACID,
    TAC_TIPO_ACID,
    ANO,
    MES,
    AVG(TOTAL_ACIDENTES) AS MEDIA_ACIDENTES_MENSAL  
FROM MVIEW_TIPOS_CLASSIFICACOES_ACIDENTES
GROUP BY TAC_CLASS_ACID, TAC_TIPO_ACID, ANO, MES
ORDER BY TAC_CLASS_ACID, TAC_TIPO_ACID, ANO, MES;


-- CONSULTA 08: RANKING DOS TIPOS DE ACIDENTES COM MAIS VITIMAS FATAIS
SELECT
    TAC_TIPO_ACID,
    SUM(VITIMAS_FATAIS) AS TOTAL_VITIMAS_FATAIS,
    RANK() OVER (ORDER BY SUM(VITIMAS_FATAIS) DESC) AS RANKING_FATAL
FROM MVIEW_TIPOS_CLASSIFICACOES_ACIDENTES
GROUP BY TAC_TIPO_ACID  
ORDER BY TOTAL_VITIMAS_FATAIS DESC;

