SELECT
    *
FROM (SELECT 
        R.ROD_CODIGO_RODOVIA AS CODIGO_RODOVIA,
        R.ROD_DENOMINACAO AS DENOMINACAO_RODOVIA,
        M.MUN_MUNICIPIO AS MUNICIPIO,    
        A.ACD_MES AS MES, 
        A.ACD_ANO AS ANO,        
        SUM(A.ACD_ILESA_INT) AS VITIMAS_ILESAS,
        SUM(A.ACD_VIT_FATAL_INT) AS VITIMAS_FATAIS,
        SUM(A.ACD_VIT_GRAVE_INT) AS VITIMAS_GRAVES,
        SUM(A.ACD_VIT_LEVE_INT) AS VITIMAS_LEVES,
        SUM(A.ACD_VIT_MODERADA_INT) AS VITIMAS_MODERADAS,
        SUM(A.ACD_VIT_SEMINFO_INT) AS VITIMAS_SEM_INFO,
        COUNT(A.ACD_ID) AS TOTAL_ACIDENTES
    FROM APP.ACIDENTES A
    JOIN APP.MUNICIPIOS M   ON A.ACD_MUN_ID = M.MUN_ID
    JOIN APP.RODOVIAS R     ON R.ROD_ID = A.ACD_ROD_ID
    GROUP BY R.ROD_CODIGO_RODOVIA, R.ROD_DENOMINACAO, M.MUN_MUNICIPIO, A.ACD_MES, A.ACD_ANO
    
    UNION ALL
    
    SELECT 
        H_R.ROD_CODIGO_RODOVIA AS CODIGO_RODOVIA,
        H_R.ROD_DENOMINACAO AS DENOMINACAO_RODOVIA,
        H_M.MUN_MUNICIPIO AS MUNICIPIO,
        H_A.H_ACD_MES AS MES, 
        H_A.H_ACD_ANO AS ANO,
        SUM(H_A.H_ACD_ILESA_INT) AS VITIMAS_ILESAS,
        SUM(H_A.H_ACD_VIT_FATAL_INT) AS VITIMAS_FATAIS,
        SUM(H_A.H_ACD_VIT_GRAVE_INT) AS VITIMAS_GRAVES,
        SUM(H_A.H_ACD_VIT_LEVE_INT) AS VITIMAS_LEVES,
        SUM(H_A.H_ACD_VIT_MODERADA_INT) AS VITIMAS_MODERADAS,
        SUM(H_A.H_ACD_VIT_SEMINFO_INT) AS VITIMAS_SEM_INFO,
        COUNT(H_A.H_ACD_ID) AS TOTAL_ACIDENTES
    FROM APP.H_ACIDENTES H_A
    JOIN APP.MUNICIPIOS H_M ON H_A.H_ACD_MUN_ID = H_M.MUN_ID
    JOIN APP.RODOVIAS H_R ON H_A.H_ACD_ROD_ID = H_R.ROD_ID
    GROUP BY H_R.ROD_CODIGO_RODOVIA, H_R.ROD_DENOMINACAO, H_M.MUN_MUNICIPIO, H_A.H_ACD_MES, H_A.H_ACD_ANO)

ORDER BY DENOMINACAO_RODOVIA;





-- SELECT 
--    column_name
--FROM   all_tab_cols
--WHERE  table_name = 'MUNICIPIOS';



