SELECT
    VEICULO,
    VE.VEN_QTD,
    AC.ACD_ID,
    AC.ACD_ANO,
    AC.ACD_MES,
    AC.ACD_ILESA_INT,
    AC.ACD_VIT_FATAL_INT,
    AC.ACD_VIT_GRAVE_INT,
    AC.ACD_VIT_LEVE_INT,
    AC.ACD_VIT_MODERADA_INT,
    AC.ACD_VIT_SEMINFO_INT

FROM VIEW_TODOS_VEICULOS_ENVOLVIDOS VE
LEFT JOIN APP.TIPOS_VEICULOS TV ON VE.VEN_TVC_ID = TV.TVC_ID
LEFT JOIN VIEW_TODOS_ACIDENTES AC ON AC.ACD_ID = VE.VEN_ACD_ID;

