
-- VIEW 01: PERFIL DE RISCO POR CONCESSIONÁRIA E RODOVIA
CREATE VIEW VIEW_ACIDENTES_POR_RODOVIA_CONCESSIONARIA AS
SELECT
    C.CON_CONCESSIONARIA,
    R.ROD_CODIGO_RODOVIA,
    COUNT(A.ACD_ID) AS TOTAL_ACIDENTES,
    SUM(A.ACD_VIT_FATAL_INT) AS TOTAL_MORTES
FROM APP.ACIDENTES A
JOIN APP.RODOVIAS R ON A.ACD_ROD_ID = R.ROD_ID
JOIN APP.CONCESSIONARIAS C ON R.ROD_CON_ID = C.CON_ID
GROUP BY C.CON_CONCESSIONARIA, R.ROD_CODIGO_RODOVIA
ORDER BY TOTAL_MORTES DESC, TOTAL_ACIDENTES DESC;

-- VIEW 02: IMPACTO DAS CONDIÇÕES CLIMÁTICAS NA GRAVIDADE DO ACIDENTE
CREATE VIEW VIEW_IMPACTO_CLIMA_NA_GRAVIDADE_ACIDENTE AS
SELECT
    CC.CCM_METEORO,
    CC.CCM_VISIB,
    COUNT(A.ACD_ID) AS TOTAL_ACIDENTES,
    ROUND(AVG(A.ACD_VIT_FATAL_INT + A.ACD_VIT_GRAVE_INT), 2) AS MEDIA_VITIMAS_GRAVES_FATAIS
FROM APP.ACIDENTES A
JOIN APP.CONDICOES_CLIMATICAS CC ON A.ACD_CCM_ID = CC.CCM_ID
GROUP BY CC.CCM_METEORO, CC.CCM_VISIB
ORDER BY MEDIA_VITIMAS_GRAVES_FATAIS DESC;

-- VIEW 03: TOPOLOGIA DE ACIDENTES POR TIPO DE VEÍCULO
CREATE VIEW VIEW_VEICULOS_ACIDENTE_FATAL AS
SELECT
    TV.TVC_VEICULO,
    SUM(VE.VEN_QTD) AS TOTAL_VEICULOS_ENVOLVIDOS,
    SUM(CASE WHEN A.ACD_VIT_FATAL_INT > 0 THEN VE.VEN_QTD ELSE 0 END) AS VEICULOS_EM_ACIDENTES_FATAIS
FROM APP.VEICULOS_ENVOLVIDOS VE
JOIN APP.TIPOS_VEICULOS TV ON VE.VEN_TVC_ID = TV.TVC_ID
JOIN APP.ACIDENTES A ON VE.VEN_ACD_ID = A.ACD_ID
GROUP BY TV.TVC_VEICULO
ORDER BY VEICULOS_EM_ACIDENTES_FATAIS DESC;

-- VIEW 04: CLASSIFICAÇÃO DOS ACIDENTES MAIS COMUNS E MORTAIS
CREATE VIEW VIEW_ACIDENTES_MAIS_FATAIS AS
SELECT
    TA.TAC_CLASS_ACID,
    TA.TAC_TIPO_ACID,
    COUNT(A.ACD_ID) AS TOTAL_ACIDENTES,
    SUM(A.ACD_VIT_FATAL_INT) AS TOTAL_FATAIS
FROM APP.ACIDENTES A
JOIN APP.TIPOS_ACIDENTES TA ON A.ACD_TAC_ID = TA.TAC_ID
GROUP BY TA.TAC_CLASS_ACID, TA.TAC_TIPO_ACID
ORDER BY TOTAL_FATAIS DESC, TOTAL_ACIDENTES DESC;

-- VIEW 05: PICOS TEMPORAIS (SAZONALIDADE E HORÁRIO)
CREATE VIEW VIEW_PERIODO_MAIS_ACIDENTES AS
SELECT
    EXTRACT(HOUR FROM ACD_DTHR_OC) AS HORA_DIA,
    ACD_MES,
    COUNT(ACD_ID) AS TOTAL_ACIDENTES
FROM APP.ACIDENTES
GROUP BY EXTRACT(HOUR FROM ACD_DTHR_OC), ACD_MES
ORDER BY TOTAL_ACIDENTES DESC;

-- VIEW 06: PONTOS CRÍTICOS (HOTSPOTS) POR QUILOMETRAGEM
CREATE VIEW VIEW_LOCALIZACOES_COM_MAIS_ACIDENTES AS
SELECT
    R.ROD_CODIGO_RODOVIA,
    A.ACD_MARCO_QM,
    A.ACD_TIPO_PISTA, -- Incluir o tipo de pista (simples/dupla) como contexto
    COUNT(A.ACD_ID) AS CONCENTRACAO_ACIDENTES
FROM APP.ACIDENTES A
JOIN APP.RODOVIAS R ON A.ACD_ROD_ID = R.ROD_ID
GROUP BY R.ROD_CODIGO_RODOVIA, A.ACD_MARCO_QM, A.ACD_TIPO_PISTA
HAVING COUNT(A.ACD_ID) > 5 -- Filtro para mostrar apenas hotspots (ajustável)
ORDER BY CONCENTRACAO_ACIDENTES DESC;

-- VIEW 07: RISCO GEOGRÁFICO: MUNICÍPIOS E REGIONAL ADMINISTRATIVA
CREATE VIEW VIEW_ACIDENTES_POR_REGIAO AS
SELECT
    M.MUN_REG_ADM,
    M.MUN_REG_DER,
    COUNT(A.ACD_ID) AS ACIDENTES_NA_REGIONAL,
    SUM(A.ACD_VIT_FATAL_INT) AS TOTAL_MORTES
FROM APP.ACIDENTES A
JOIN APP.MUNICIPIOS M ON A.ACD_MUN_ID = M.MUN_ID
GROUP BY M.MUN_REG_ADM, M.MUN_REG_DER
ORDER BY TOTAL_MORTES DESC;

-- VIEW 08: Cenários de Alto Risco (Condição + Tipo de Acidente + Pista)
CREATE VIEW VIEW_COMBINACAO_COM_MAIS_ACIDENTES AS
SELECT
    A.ACD_TIPO_PISTA,
    TA.TAC_TIPO_ACID,
    CC.CCM_METEORO,
    COUNT(A.ACD_ID) AS Total_Acidentes,
    -- Calcular a média de vítimas (total) por acidente neste cenário
    ROUND(AVG(
        A.ACD_ILESA_INT + 
        A.ACD_VIT_FATAL_INT + 
        A.ACD_VIT_GRAVE_INT + 
        A.ACD_VIT_LEVE_INT + 
        A.ACD_VIT_MODERADA_INT + 
        A.ACD_VIT_SEMINFO_INT
    ), 2) AS Media_Vitimas_Por_Acidente
FROM APP.ACIDENTES A
JOIN APP.TIPOS_ACIDENTES TA ON A.ACD_TAC_ID = TA.TAC_ID
JOIN APP.CONDICOES_CLIMATICAS CC ON A.ACD_CCM_ID = CC.CCM_ID
GROUP BY A.ACD_TIPO_PISTA, TA.TAC_TIPO_ACID, CC.CCM_METEORO
HAVING COUNT(A.ACD_ID) >= 10 -- Filtrar combinações com ocorrência mínima para relevância estatística (ajustável)
ORDER BY Media_Vitimas_Por_Acidente DESC;