--------------------------------------------------------
--  DDL for Trigger TG_AUD_CONCESSIONARIA
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_CONCESSIONARIA" 
AFTER UPDATE OR DELETE ON CONCESSIONARIAS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR(20);
    V_TABELA VARCHAR(30) := 'CONCESSIONARIAS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, NULL, NULL, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.CON_ID <> :OLD.CON_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'CON_ID', :OLD.CON_ID, :NEW.CON_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.CON_CONCESSIONARIA <> :OLD.CON_CONCESSIONARIA) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'CON_CONCESSIONARIA', :OLD.CON_CONCESSIONARIA, :NEW.CON_CONCESSIONARIA, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_CONCESSIONARIA" ENABLE;

--------------------------------------------------------
--  DDL for Trigger TG_AUD_RODOVIAS
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_RODOVIAS" 
AFTER UPDATE OR DELETE ON RODOVIAS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR(20);
    V_TABELA VARCHAR(30) := 'RODOVIAS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, NULL, NULL, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.ROD_ID <> :OLD.ROD_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ROD_ID', :OLD.ROD_ID, :NEW.ROD_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ROD_CODIGO_RODOVIA <> :OLD.ROD_CODIGO_RODOVIA) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ROD_CODIGO_RODOVIA', :OLD.ROD_CODIGO_RODOVIA, :NEW.ROD_CODIGO_RODOVIA, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ROD_DENOMINACAO <> :OLD.ROD_DENOMINACAO) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ROD_DENOMINACAO', :OLD.ROD_DENOMINACAO, :NEW.ROD_DENOMINACAO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ROD_JURISDICAO <> :OLD.ROD_JURISDICAO) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ROD_JURISDICAO', :OLD.ROD_JURISDICAO, :NEW.ROD_JURISDICAO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ROD_CON_ID <> :OLD.ROD_CON_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ROD_CON_ID', :OLD.ROD_CON_ID, :NEW.ROD_CON_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_RODOVIAS" ENABLE;

--------------------------------------------------------
--  DDL for Trigger TG_AUD_MUNICIPIOS
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_MUNICIPIOS" 
AFTER UPDATE OR DELETE ON MUNICIPIOS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR(20);
    V_TABELA VARCHAR(30) := 'MUNICIPIOS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, NULL, NULL, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.MUN_ID <> :OLD.MUN_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'MUN_ID', :OLD.MUN_ID, :NEW.MUN_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.MUN_MUNICIPIO <> :OLD.MUN_MUNICIPIO) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'MUN_MUNICIPIO', :OLD.MUN_MUNICIPIO, :NEW.MUN_MUNICIPIO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.MUN_REG_DER <> :OLD.MUN_REG_DER) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'MUN_REG_DER', :OLD.MUN_REG_DER, :NEW.MUN_REG_DER, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.MUN_REG_ADM <> :OLD.MUN_REG_ADM) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'MUN_REG_ADM', :OLD.MUN_REG_ADM, :NEW.MUN_REG_ADM, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_MUNICIPIOS" ENABLE;

--------------------------------------------------------
--  DDL for Trigger TG_AUD_TIPOS_ACIDENTES
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_TIPOS_ACIDENTES" 
AFTER UPDATE OR DELETE ON TIPOS_ACIDENTES
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR(20);
    V_TABELA VARCHAR(30) := 'TIPOS_ACIDENTES';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, NULL, NULL, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.TAC_ID <> :OLD.TAC_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'TAC_ID', :OLD.TAC_ID, :NEW.TAC_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.TAC_CLASS_ACID <> :OLD.TAC_CLASS_ACID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'TAC_CLASS_ACID', :OLD.TAC_CLASS_ACID, :NEW.TAC_CLASS_ACID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.TAC_TIPO_ACID <> :OLD.TAC_TIPO_ACID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'TAC_TIPO_ACID', :OLD.TAC_TIPO_ACID, :NEW.TAC_TIPO_ACID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_TIPOS_ACIDENTES" ENABLE;

--------------------------------------------------------
--  DDL for Trigger TG_AUD_CONDICOES_CLIMATICAS
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_CONDICOES_CLIMATICAS" 
AFTER UPDATE OR DELETE ON CONDICOES_CLIMATICAS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR(20);
    V_TABELA VARCHAR(30) := 'CONDICOES_CLIMATICAS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, NULL, NULL, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.CCM_ID <> :OLD.CCM_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'CCM_ID', :OLD.CCM_ID, :NEW.CCM_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.CCM_METEORO <> :OLD.CCM_METEORO) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'CCM_METEORO', :OLD.CCM_METEORO, :NEW.CCM_METEORO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.CCM_VISIB <> :OLD.CCM_VISIB) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'CCM_VISIB', :OLD.CCM_VISIB, :NEW.CCM_VISIB, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_CONDICOES_CLIMATICAS" ENABLE;

--------------------------------------------------------
--  DDL for Trigger TG_AUD_TIPOS_VEICULOS
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_TIPOS_VEICULOS" 
AFTER UPDATE OR DELETE ON TIPOS_VEICULOS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR(20);
    V_TABELA VARCHAR(30) := 'TIPOS_VEICULOS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, NULL, NULL, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.TVC_ID <> :OLD.TVC_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'TVC_ID', :OLD.TVC_ID, :NEW.TVC_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.TVC_VEICULO <> :OLD.TVC_VEICULO) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'TVC_VEICULO', :OLD.TVC_VEICULO, :NEW.TVC_VEICULO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_TIPOS_VEICULOS" ENABLE;

--------------------------------------------------------
--  DDL for Trigger TG_AUD_ACIDENTES
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_ACIDENTES" 
AFTER UPDATE OR DELETE ON ACIDENTES
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR(20);
    V_TABELA VARCHAR(30) := 'ACIDENTES';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, NULL, NULL, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.ACD_ID <> :OLD.ACD_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_ID', :OLD.ACD_ID, :NEW.ACD_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_MARCO_QM <> :OLD.ACD_MARCO_QM) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_MARCO_QM', :OLD.ACD_MARCO_QM, :NEW.ACD_MARCO_QM, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_SENTIDO <> :OLD.ACD_SENTIDO) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_SENTIDO', :OLD.ACD_SENTIDO, :NEW.ACD_SENTIDO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_DTHR_OC <> :OLD.ACD_DTHR_OC) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_DTHR_OC', :OLD.ACD_DTHR_OC, :NEW.ACD_DTHR_OC, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_ANO <> :OLD.ACD_ANO) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_ANO', :OLD.ACD_ANO, :NEW.ACD_ANO, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_MES <> :OLD.ACD_MES) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_MES', :OLD.ACD_MES, :NEW.ACD_MES, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_ILESA_INT <> :OLD.ACD_ILESA_INT) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_ILESA_INT', :OLD.ACD_ILESA_INT, :NEW.ACD_ILESA_INT, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_VIT_FATAL_INT <> :OLD.ACD_VIT_FATAL_INT) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_VIT_FATAL_INT', :OLD.ACD_VIT_FATAL_INT, :NEW.ACD_VIT_FATAL_INT, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_VIT_GRAVE_INT <> :OLD.ACD_VIT_GRAVE_INT) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_VIT_GRAVE_INT', :OLD.ACD_VIT_GRAVE_INT, :NEW.ACD_VIT_GRAVE_INT, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_VIT_LEVE_INT <> :OLD.ACD_VIT_LEVE_INT) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_VIT_LEVE_INT', :OLD.ACD_VIT_LEVE_INT, :NEW.ACD_VIT_LEVE_INT, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_VIT_MODERADA_INT <> :OLD.ACD_VIT_MODERADA_INT) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_VIT_MODERADA_INT', :OLD.ACD_VIT_MODERADA_INT, :NEW.ACD_VIT_MODERADA_INT, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_VIT_SEMINFO_INT <> :OLD.ACD_VIT_SEMINFO_INT) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_VIT_SEMINFO_INT', :OLD.ACD_VIT_SEMINFO_INT, :NEW.ACD_VIT_SEMINFO_INT, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_TIPO_PISTA <> :OLD.ACD_TIPO_PISTA) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_TIPO_PISTA', :OLD.ACD_TIPO_PISTA, :NEW.ACD_TIPO_PISTA, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_LAT_FINAL <> :OLD.ACD_LAT_FINAL) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_LAT_FINAL', :OLD.ACD_LAT_FINAL, :NEW.ACD_LAT_FINAL, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_LON_FINAL <> :OLD.ACD_LON_FINAL) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_LON_FINAL', :OLD.ACD_LON_FINAL, :NEW.ACD_LON_FINAL, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_ROD_ID <> :OLD.ACD_ROD_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_ROD_ID', :OLD.ACD_ROD_ID, :NEW.ACD_ROD_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_TAC_ID <> :OLD.ACD_TAC_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_TAC_ID', :OLD.ACD_TAC_ID, :NEW.ACD_TAC_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_CCM_ID <> :OLD.ACD_CCM_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_CCM_ID', :OLD.ACD_CCM_ID, :NEW.ACD_CCM_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.ACD_MUN_ID <> :OLD.ACD_MUN_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'ACD_MUN_ID', :OLD.ACD_MUN_ID, :NEW.ACD_MUN_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_ACIDENTES" ENABLE;

--------------------------------------------------------
--  DDL for Trigger TG_AUD_VEICULOS_ENVOLVIDOS
--------------------------------------------------------
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TG_AUD_VEICULOS_ENVOLVIDOS" 
AFTER UPDATE OR DELETE ON VEICULOS_ENVOLVIDOS
FOR EACH ROW
DECLARE
    V_USU_BD VARCHAR(30);
    V_USU_SO VARCHAR(255) := SYS_CONTEXT('USERENV','OS_USER');
    V_TP_OPERACAO CHAR(1);
    V_ROWID VARCHAR(20);
    V_TABELA VARCHAR(30) := 'VEICULOS_ENVOLVIDOS';
BEGIN
    SELECT USER INTO V_USU_BD FROM DUAL;
    V_ROWID := :OLD.ROWID;
    IF DELETING THEN
        V_TP_OPERACAO := 'D';
        AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, NULL, NULL, NULL, V_USU_BD, V_USU_SO, SYSDATE);
    ELSE
        V_TP_OPERACAO := 'U';
        IF (:NEW.VEN_ID <> :OLD.VEN_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'VEN_ID', :OLD.VEN_ID, :NEW.VEN_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.VEN_QTD <> :OLD.VEN_QTD) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'VEN_QTD', :OLD.VEN_QTD, :NEW.VEN_QTD, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.VEN_ACD_ID <> :OLD.VEN_ACD_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'VEN_ACD_ID', :OLD.VEN_ACD_ID, :NEW.VEN_ACD_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
        IF (:NEW.VEN_TVC_ID <> :OLD.VEN_TVC_ID) THEN
            AUDITORIA.PROC_AUDITORIA(V_TABELA, V_ROWID, V_TP_OPERACAO, 'VEN_TVC_ID', :OLD.VEN_TVC_ID, :NEW.VEN_TVC_ID, V_USU_BD, V_USU_SO, SYSDATE);
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TG_AUD_VEICULOS_ENVOLVIDOS" ENABLE;