DROP TRIGGER TRG_MUNICIPIOS_INSERT;
DROP TRIGGER TRG_CONDICOES_CLIMATICAS_INSERT;
DROP TRIGGER TRG_CONCESSIONARIAS_INSERT;
DROP TRIGGER TRG_RODOVIAS_INSERT;
DROP TRIGGER TRG_TIPOS_ACIDENTES_INSERT;
DROP TRIGGER TRG_TIPOS_VEICULOS_INSERT;
DROP TRIGGER TRG_ACIDENTES_INSERT;
DROP TRIGGER TRG_VEICULOS_ENVOLVIDOS_INSERT;

DROP SEQUENCE SEQ_MUNICIPIOS_ID;
DROP SEQUENCE SEQ_CONCESSIONARIAS_ID;
DROP SEQUENCE SEQ_RODOVIAS_ID;
DROP SEQUENCE SEQ_CONDICOES_CLIMATICAS_ID;
DROP SEQUENCE SEQ_TIPOS_ACIDENTES_ID;
DROP SEQUENCE SEQ_TIPOS_VEICULOS_ID;
DROP SEQUENCE SEQ_ACIDENTES_ID;
DROP SEQUENCE SEQ_VEICULOS_ENVOLVIDOS_ID;
DROP SEQUENCE SEQ_DADOS_ID;

DROP TABLE VEICULOS_ENVOLVIDOS;
DROP TABLE ACIDENTES;
DROP TABLE TIPOS_VEICULOS;
DROP TABLE TIPOS_ACIDENTES;
DROP TABLE RODOVIAS;
DROP TABLE CONCESSIONARIAS;
DROP TABLE CONDICOES_CLIMATICAS;
DROP TABLE MUNICIPIOS;
DROP TABLE DADOS;