--------------------------------------------------------------------------------
--  TABELAS                                                                   --
--  SCRIPTS PARA CRIAR OS SCHEMAS DAS TABELAS                                 --
--------------------------------------------------------------------------------

CREATE TABLE MUNICIPIOS (
    MUN_ID NUMBER (38), 
    MUN_MUNICIPIO VARCHAR2(100) NOT NULL,
    MUN_REG_DER VARCHAR2(100) NOT NULL,
    MUN_REG_ADM VARCHAR2(100) NOT NULL
);

CREATE TABLE CONDICOES_CLIMATICAS (
    CCM_ID NUMBER(38), 
    CCM_METEORO VARCHAR2(100) NOT NULL,
    CCM_VISIB VARCHAR2(100) NOT NULL
);

CREATE TABLE CONCESSIONARIAS (
    CON_ID NUMBER (38), 
    CON_CONCESSIONARIA VARCHAR2(100) NOT NULL
);

CREATE TABLE RODOVIAS (
    ROD_ID NUMBER(38), 
    ROD_CODIGO_RODOVIA VARCHAR2(100) NOT NULL,
    ROD_DENOMINACAO VARCHAR2(100),
    ROD_JURISDICAO VARCHAR2(100),
    ROD_CON_ID NUMBER(38) NOT NULL
);

CREATE TABLE TIPOS_ACIDENTES (
    TAC_ID NUMBER(38), 
    TAC_CLASS_ACID VARCHAR2(100),
    TAC_TIPO_ACID VARCHAR2(100)
);

CREATE TABLE TIPOS_VEICULOS (
    TVC_ID NUMBER (38), 
    TVC_VEICULO VARCHAR2(100)
);

CREATE TABLE ACIDENTES (
    ACD_ID NUMBER(38),
    ACD_MARCO_QM NUMBER(38) NOT NULL,
    ACD_SENTIDO VARCHAR2(100) NOT NULL,
    ACD_DTHR_OC TIMESTAMP NOT NULL,
    ACD_ANO NUMBER(38) NOT NULL,
    ACD_MES NUMBER(38) NOT NULL,
    ACD_ILESA_INT NUMBER(38) NOT NULL,
    ACD_VIT_FATAL_INT NUMBER(38) NOT NULL,
    ACD_VIT_GRAVE_INT NUMBER(38) NOT NULL,
    ACD_VIT_LEVE_INT NUMBER(38) NOT NULL,
    ACD_VIT_MODERADA_INT NUMBER(38) NOT NULL,
    ACD_VIT_SEMINFO_INT NUMBER(38) NOT NULL,
    ACD_TIPO_PISTA VARCHAR2(100) NOT NULL,
    ACD_LAT_FINAL NUMBER(38) NOT NULL,
    ACD_LON_FINAL NUMBER(38) NOT NULL,
    ACD_ROD_ID NUMBER(38) NOT NULL,
    ACD_TAC_ID NUMBER(38) NOT NULL,
    ACD_CCM_ID NUMBER(38) NOT NULL,
    ACD_MUN_ID NUMBER(38)
);

CREATE TABLE VEICULOS_ENVOLVIDOS (
    VEN_ID NUMBER(38),
    VEN_QTD NUMBER(38) NOT NULL,
    VEN_ACD_ID NUMBER(38) NOT NULL,
    VEN_TVC_ID NUMBER(38) NOT NULL
);

--------------------------------------------------------------------------------
--  CONTRAINTS                                                                --
--  SCRIPTS PARA CRIAR AS CONTRAINTS DAS ENTIDADES                            --
--------------------------------------------------------------------------------

-- CRIAÇÃO DAS CONTRAINTS: MUNICIPIOS
ALTER TABLE MUNICIPIOS
ADD CONSTRAINT PK_MUNICIPIOS UNIQUE (MUN_ID);

ALTER TABLE MUNICIPIOS
ADD CONSTRAINT UQ_MUNICIPIOS UNIQUE (MUN_MUNICIPIO, MUN_REG_ADM, MUN_REG_DER);


-- CRIAÇÃO DAS CONTRAINTS: CONDICOES CLIMATICAS
ALTER TABLE CONDICOES_CLIMATICAS
ADD CONSTRAINT PK_CONDICOES_CLIMATICAS PRIMARY KEY (CCM_ID);

ALTER TABLE CONDICOES_CLIMATICAS
ADD CONSTRAINT UQ_CONDICOES_CLIMATICAS UNIQUE (CCM_METEORO, CCM_VISIB);


-- CRIAÇÃO DAS CONTRAINTS: CONCESSIONARIAS
ALTER TABLE CONCESSIONARIAS
ADD CONSTRAINT PK_CONCESSIONARIAS PRIMARY KEY (CON_ID);

ALTER TABLE CONCESSIONARIAS
ADD CONSTRAINT UQ_CONCESSIONARIAS UNIQUE (CON_CONCESSIONARIA);


-- CRIAÇÃO DAS CONTRAINTS: RODOVIAS
ALTER TABLE RODOVIAS
ADD CONSTRAINT PK_RODOVIAS PRIMARY KEY (ROD_ID);

ALTER TABLE RODOVIAS
ADD CONSTRAINT UQ_RODOVIAS UNIQUE (ROD_CODIGO_RODOVIA, ROD_DENOMINACAO, ROD_JURISDICAO, ROD_CON_ID);

ALTER TABLE RODOVIAS
ADD CONSTRAINT FK_RODOVIAS_CONCESSIONARIAS FOREIGN KEY (ROD_CON_ID)
    REFERENCES CONCESSIONARIAS(CON_ID);


-- CRIAÇÃO DAS CONTRAINTS: TIPOS_ACIDENTES
ALTER TABLE TIPOS_ACIDENTES
ADD CONSTRAINT PK_TIPOS_ACIDENTES PRIMARY KEY (TAC_ID);

ALTER TABLE TIPOS_ACIDENTES
ADD CONSTRAINT UQ_TIPOS_ACIDENTES UNIQUE (TAC_CLASS_ACID, TAC_TIPO_ACID);


-- CRIAÇÃO DAS CONTRAINTS: TIPOS_VEICULOS
ALTER TABLE TIPOS_VEICULOS
ADD CONSTRAINT PK_TIPOS_VEICULOS PRIMARY KEY (TVC_ID);

ALTER TABLE TIPOS_VEICULOS
ADD CONSTRAINT UQ_TIPOS_VEICULOS UNIQUE (TVC_VEICULO);


-- CRIAÇÃO DAS CONTRAINTS: ACIDENTES
ALTER TABLE ACIDENTES
ADD CONSTRAINT PK_ACIDENTES PRIMARY KEY (ACD_ID);

ALTER TABLE ACIDENTES
ADD CONSTRAINT FK_ACIDENTES_RODOVIAS FOREIGN KEY(ACD_ROD_ID) REFERENCES RODOVIAS(ROD_ID);

ALTER TABLE ACIDENTES
ADD CONSTRAINT FK_ACIDENTES_TIPOS_ACIDENTES FOREIGN KEY(ACD_TAC_ID) REFERENCES TIPOS_ACIDENTES(TAC_ID);

ALTER TABLE ACIDENTES
ADD CONSTRAINT FK_ACIDENTES_CONDICOES_CLIMATICAS FOREIGN KEY(ACD_CCM_ID) REFERENCES CONDICOES_CLIMATICAS(CCM_ID);

ALTER TABLE ACIDENTES
ADD CONSTRAINT FK_ACIDENTES_MUNICIPIOS FOREIGN KEY(ACD_MUN_ID) REFERENCES MUNICIPIOS(MUN_ID);


-- CRIAÇÃO DAS CONTRAINTS: VEICULOS_ENVOLVIDOS
ALTER TABLE VEICULOS_ENVOLVIDOS
ADD CONSTRAINT PK_VEICULOS_ENVOLVIDOS PRIMARY KEY (VEN_ID);

ALTER TABLE VEICULOS_ENVOLVIDOS
ADD CONSTRAINT FK_VEICULOS_ENVOLVIDOS_ACIDENTES FOREIGN KEY(VEN_ACD_ID) REFERENCES ACIDENTES(ACD_ID);

ALTER TABLE VEICULOS_ENVOLVIDOS
ADD CONSTRAINT FK_VEICULOS_ENVOLVIDOS_TIPOS_VEICULOS FOREIGN KEY(VEN_TVC_ID) REFERENCES TIPOS_VEICULOS(TVC_ID);
