CREATE OR REPLACE TRIGGER TRG_MUNICIPIOS_INSERT
BEFORE INSERT ON MUNICIPIOS
FOR EACH ROW
WHEN (NEW.MUN_ID IS NULL)
BEGIN
  -- Atribui o próximo valor da sequence ao campo MUN_ID
  :NEW.MUN_ID := SEQ_MUNICIPIOS_ID.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CONCESSIONARIAS_INSERT
BEFORE INSERT ON CONCESSIONARIAS
FOR EACH ROW
WHEN (NEW.CON_ID IS NULL)
BEGIN
  -- Atribui o próximo valor da sequence ao campo CON_ID
  :NEW.CON_ID := SEQ_CONCESSIONARIAS_ID.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_RODOVIAS_INSERT
BEFORE INSERT ON RODOVIAS
FOR EACH ROW
WHEN (NEW.ROD_ID IS NULL)
BEGIN
  -- Atribui o próximo valor da sequence ao campo ROD_ID
  :NEW.ROD_ID := SEQ_RODOVIAS_ID.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CONDICOES_CLIMATICAS_INSERT
BEFORE INSERT ON CONDICOES_CLIMATICAS
FOR EACH ROW
WHEN (NEW.CCM_ID IS NULL)
BEGIN
  -- Atribui o próximo valor da sequence ao campo CCM_ID
  :NEW.CCM_ID := SEQ_CONDICOES_CLIMATICAS_ID.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_TIPOS_ACIDENTES_INSERT
BEFORE INSERT ON TIPOS_ACIDENTES
FOR EACH ROW
WHEN (NEW.TAC_ID IS NULL)
BEGIN
  -- Atribui o próximo valor da sequence ao campo TAC_ID
  :NEW.TAC_ID := SEQ_TIPOS_ACIDENTES_ID.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_TIPOS_VEICULOS_INSERT
BEFORE INSERT ON TIPOS_VEICULOS
FOR EACH ROW
WHEN (NEW.TVC_ID IS NULL)
BEGIN
  -- Atribui o próximo valor da sequence ao campo TVC_ID
  :NEW.TVC_ID := SEQ_TIPOS_VEICULOS_ID.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER TRG_ACIDENTES_INSERT
BEFORE INSERT ON ACIDENTES
FOR EACH ROW
WHEN (NEW.ACD_ID IS NULL)
BEGIN
  -- Atribui o próximo valor da sequence ao campo ACD_ID
  :NEW.ACD_ID := SEQ_ACIDENTES_ID.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_VEICULOS_ENVOLVIDOS_INSERT
BEFORE INSERT ON VEICULOS_ENVOLVIDOS
FOR EACH ROW
WHEN (NEW.VEN_ID IS NULL)
BEGIN
  -- Atribui o próximo valor da sequence ao campo VEN_ID
  :NEW.VEN_ID := SEQ_VEICULOS_ENVOLVIDOS_ID.NEXTVAL;
END;
/


